added command bin/finddep, added copyright headers to misc bin/ scripts

diff --git a/bin/foamClearPolyMesh b/bin/foamClearPolyMesh
--- a/bin/foamClearPolyMesh
+++ b/bin/foamClearPolyMesh
@@ -32,8 +32,8 @@
 #
 #------------------------------------------------------------------------------
 usage() {
-   while [ "$#" -ge 1 ]; do echo "$1" 1>&2; shift; done
-   cat <<USAGE 1>&2
+    while [ "$#" -ge 1 ]; do echo "$1" 1>&2; shift; done
+    cat <<USAGE 1>&2
 
 usage: ${0##*/} [-case dir] [-region name]
 
@@ -49,62 +49,62 @@ unset caseDir regionName
 # parse a single option
 while [ "$#" -gt 0 ]
 do
-   case "$1" in
-   -h | -help)
-      usage
-      ;;
-   -case)
-      [ "$#" -ge 2 ] || usage "'-case' option requires an argument"
-      caseDir=$2
-      shift 2
-      cd "$caseDir" 2>/dev/null || usage "directory does not exist:  '$caseDir'"
-      ;;
-   -region)
-      [ "$#" -ge 2 ] || usage "'-region' option requires an argument"
-      regionName=$2
-      shift 2
-      ;;
-   *)
-      usage "unknown option/argument: '$*'"
-      ;;
-   esac
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -case)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+        cd "$2" 2>/dev/null || usage "directory does not exist:  '$2'"
+        caseDir=$2
+        shift 2
+        ;;
+    -region)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+        regionName=$2
+        shift 2
+        ;;
+    *)
+        usage "unknown option/argument: '$*'"
+        ;;
+    esac
 done
 
 if [ -n "$regionName" ]
 then
-   meshDir=$regionName/polyMesh
+    meshDir=$regionName/polyMesh
 else
-   meshDir=polyMesh
+    meshDir=polyMesh
 fi
 
 # if -case was specified: insist upon 'constant/polyMesh'
 if [ -n "$caseDir" ]
 then
-   if [ -d constant/$meshDir ]
-   then
-      # use constant/polyMesh
-      meshDir=constant/$meshDir
-   else
-      echo "Error: no 'constant/$meshDir' in $caseDir" 1>&2
-      exit 1
-   fi
+    if [ -d constant/$meshDir ]
+    then
+        # use constant/polyMesh
+        meshDir=constant/$meshDir
+    else
+       echo "Error: no 'constant/$meshDir' in $caseDir" 1>&2
+       exit 1
+    fi
 else
-   if [ -d constant/$meshDir ]
-   then
-      # use constant/polyMesh
-      meshDir=constant/$meshDir
-   elif [ -d $meshDir ]
-   then
-      # likely already in constant/ - do not adjust anything
-      :
-   elif [ "${PWD##*/}" = polyMesh -a -z "$regionName" ]
-   then
-      # apparently already within polyMesh/
-      meshDir=.
-   else
-      echo "Error: no appropriate 'polyMesh/' directory found" 1>&2
-      exit 1
-   fi
+    if [ -d constant/$meshDir ]
+    then
+        # use constant/polyMesh
+        meshDir=constant/$meshDir
+    elif [ -d $meshDir ]
+    then
+        # likely already in constant/ - do not adjust anything
+        :
+    elif [ "${PWD##*/}" = polyMesh -a -z "$regionName" ]
+    then
+        # apparently already within polyMesh/
+        meshDir=.
+    else
+        echo "Error: no appropriate 'polyMesh/' directory found" 1>&2
+        exit 1
+    fi
 fi
 
 
@@ -114,21 +114,21 @@ fi
 echo "Clearing ${caseDir:-.}/$meshDir" 1>&2
 
 for i in \
-   points \
-   faces \
-   owner \
-   neighbour \
-   cells \
-   boundary \
-   pointZones \
-   faceZones \
-   cellZones \
-   meshModifiers \
-   parallelData \
-   sets \
+    points \
+    faces \
+    owner \
+    neighbour \
+    cells \
+    boundary \
+    pointZones \
+    faceZones \
+    cellZones \
+    meshModifiers \
+    parallelData \
+    sets \
 ;
 do
-   rm -rf $meshDir/$i
+    rm -rf $meshDir/$i
 done
 
 #------------------------------------------------------------------------------
