foamAllHC / foamEbrowse / foamNew - error checking

diff --git a/bin/foamEbrowse b/bin/foamEbrowse
--- a/bin/foamEbrowse
+++ b/bin/foamEbrowse
@@ -41,12 +41,12 @@ if [ $# -ne 0 ]; then
    exit 1
 fi
 
+# Clean up on termination and on Ctrl-C
+trap 'rm -f $headersFile $sourcesFile 2>/dev/null; exit 0' EXIT TERM INT
+
 cd $WM_PROJECT_DIR
 find -H . -name "*.H" | fgrep -v "lnInclude" > $headersFile
 find -H . -name "*.C" | fgrep -v "lnInclude" > $sourcesFile
 ebrowse --files=$headersFile --files=$sourcesFile --output-file=.ebrowse
-
-# Clean up on termination and on Ctrl-C
-trap 'rm -f $headersFile $sourcesFile 2>/dev/null; exit 0' EXIT TERM INT
 
 #------------------------------------------------------------------------------
