STYLE: cleanup some shell script syntax

diff --git a/bin/foamJob b/bin/foamJob
--- a/bin/foamJob
+++ b/bin/foamJob
@@ -30,14 +30,14 @@
 #
 #------------------------------------------------------------------------------
 usage() {
-   while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-   cat<<USAGE
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    cat<<USAGE
 
 Usage: ${0##*/} [OPTION] <application> ...
 options:
   -case <dir>       specify alternative case directory, default is the cwd
-  -s                also sends output to screen
   -p                parallel run of processors
+  -s                also sends output to screen
   -v <ver>          specify OpenFOAM version
   -help             print the usage
 
@@ -45,56 +45,46 @@ options:
   Redirects the output to 'log' in the case directory
 
 USAGE
-   exit 1
+    exit 1
 }
 
 unset version
 
 # replacement for possibly buggy 'which'
 findExec() {
-   case "$1" in
-   */*)
-      if [ -x "$1" ] ; then
-         echo "$1"
-         return 0
-      fi
-      ;;
-   esac
+    case "$1" in
+    */*)
+        if [ -x "$1" ]
+        then
+            echo "$1"
+            return 0
+        fi
+        ;;
+    esac
 
-   oldIFS=$IFS
-   IFS=':'
-   for d in $PATH
-   do
-      # echo "testing: $d/$1" 1>&2
-      if [ -x "$d/$1" -a ! -d "$d/$1" ] ; then
-         # echo "Found exec: $d/$1" 1>&2
-         IFS=$oldIFS
-         echo "$d/$1"
-         return 0
-      fi
-   done
-   IFS=$oldIFS
-   echo ""
-   return 1
-}
-
-# grep for $1
-getPID() {
-   ps -u $LOGNAME -o 'pid,args' | fgrep "$1 " | fgrep -v grep | head -1 | awk '{ print $1 }'
+    oldIFS=$IFS
+    IFS=':'
+    for d in $PATH
+    do
+        # echo "testing: $d/$1" 1>&2
+        if [ -x "$d/$1" -a ! -d "$d/$1" ]
+        then
+            # echo "Found exec: $d/$1" 1>&2
+            IFS=$oldIFS
+            echo "$d/$1"
+            return 0
+        fi
+     done
+     IFS=$oldIFS
+     echo ""
+     return 1
 }
 
 
-consultGuide() {
-cat<<EOF
-
-Please consult the User Guide for details of parallel running
-EOF
-}
 
 # MAIN SCRIPT
 #~~~~~~~~~~~~
-SCREEN=no
-PARALLEL=no
+unset parallelOpt screenOpt
 
 
 # parse options
@@ -110,12 +100,12 @@ do
       shift 2
       cd "$caseDir" 2>/dev/null || usage "directory does not exist:  '$caseDir'"
       ;;
-   -s)
-      SCREEN=yes
+   -p)
+      parallelOpt=true
       shift
       ;;
-   -p)
-      PARALLEL=yes
+   -s)
+      screenOpt=true
       shift
       ;;
    -v)
@@ -136,100 +126,119 @@ do
    esac
 done
 
-if [ "$#" -lt 1 ]; then
-   usage "No application specified"
+if [ "$#" -lt 1 ]
+then
+    usage "No application specified"
 fi
 
 # use foamExec for a specified version and for remote (parallel) runs
-if [ -n "$version" -o "$PARALLEL" = yes ]; then
-   APPLICATION=`findExec foamExec`
-   if [ $? -ne 0 ]; then
-      usage "'foamExec' not found"
-   fi
-   if [ -n "$version" ]; then
-      APPLICATION="$APPLICATION -v $version"
-   fi
+if [ -n "$version" -o "$parallelOpt" = true ]
+then
+    APPLICATION=`findExec foamExec`
+    if [ $? -ne 0 ]
+    then
+        usage "'foamExec' not found"
+    fi
+    if [ -n "$version" ]
+    then
+        APPLICATION="$APPLICATION -v $version"
+    fi
 else
-   APPLICATION=`findExec $1`
-   if [ $? -ne 0 ]; then
-      usage "Application '$1' executable not found"
-   fi
-   echo "Application : $1"
-   shift
+    APPLICATION=`findExec $1`
+    if [ $? -ne 0 ]
+    then
+        usage "Application '$1' executable not found"
+    fi
+    echo "Application : $1"
+    shift
 fi
 
-if [ "$PARALLEL" = no ]; then
-#
-#   RUN ON SINGLE PROCESSOR
-#
-    if [ "$SCREEN" = no ]; then
-       echo "Executing: $APPLICATION $@ > log 2>&1 &"
-       $APPLICATION $@ > log 2>&1 &
+
+if [ "$parallelOpt" = true ]
+then
+    # parallel
+    # ~~~~~~~~
+
+    #
+    # is the case decomposed?
+    #
+    if [ -r "processor0" ]
+    then
+        NPROCS="`/bin/ls -1d processor* | wc -l`"
     else
-       echo "Executing: $APPLICATION $@ | tee log &"
-       $APPLICATION $@ | tee log &
-       wait $!
+        echo "Case is not currently decomposed"
+        if [ -r system/decomposeParDict ]
+        then
+            echo "system/decomposeParDict exists"
+            echo "Try decomposing with \"foamJob decomposePar\""
+            exit 1
+        else
+            echo "Cannot find system/decomposeParDict file required to decompose the case for parallel running."
+            echo "Please consult the User Guide for details of parallel running"
+            exit 1
+        fi
+    fi
+
+    #
+    # locate mpirun
+    #
+    mpirun=`findExec mpirun`
+    if [ $? -ne 0 ]
+    then
+        usage "'mpirun' not found"
+    fi
+    mpiopts="-np $NPROCS"
+
+    # 
+    # is the machine ready to run parallel?
+    #
+    echo "Parallel processing using $WM_MPLIB with $NPROCS processors"
+    case "$WM_MPLIB" in
+    OPENMPI)
+        # add hostfile info
+        for hostfile in \
+            hostfile \
+            machines \
+            system/hostfile \
+            system/machines \
+            ;
+        do
+            if [ -r $hostfile ]
+            then
+                mpiopts="$mpiopts -hostfile $hostfile"
+                break
+            fi
+        done
+        ;;
+    esac
+
+    #
+    # run (in parallel)
+    #
+    if [ "$screenOpt" = true ]
+    then
+        echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel | tee log"
+        $mpirun $mpiopts $APPLICATION $@ -parallel  | tee log
+    else
+        echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1"
+        $mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1 &
+    fi
+
+else
+    #
+    # run (on single processor)
+    #
+    if [ "$screenOpt" = true ]
+    then
+        echo "Executing: $APPLICATION $@ | tee log &"
+        $APPLICATION $@ | tee log &
+        wait $!
+    else
+        echo "Executing: $APPLICATION $@ > log 2>&1 &"
+        $APPLICATION $@ > log 2>&1 &
     fi
 else
 
-#
-#   IS THE CASE DECOMPOSED?
-#
-   if [ -r "processor0" ] ; then
-      NPROCS="`/bin/ls -1d processor* | wc -l`"
-   else
-      echo "Case is not currently decomposed"
-      if [ -r system/decomposeParDict ] ; then
-         echo "system/decomposeParDict exists"
-         echo "Try decomposing with \"foamJob decomposePar\""
-         exit 1
-      else
-         echo "Cannot find system/decomposeParDict file required to decompose the case for parallel running."
-         consultGuide
-         exit 1
-      fi
-   fi
-#
-#   LOCATE MPIRUN
-#
-   mpirun=`findExec mpirun`
-   if [ $? -ne 0 ]; then
-      usage "'mpirun' not found"
-   fi
-   mpiopts="-np $NPROCS"
-
-#
-#   IS THE MACHINE READY TO RUN PARALLEL?
-#
-   echo "Parallel processing using $WM_MPLIB with $NPROCS processors"
-   case "$WM_MPLIB" in
-   OPENMPI)
-      # add hostfile info
-      for hostfile in \
-         hostfile \
-         machines \
-         system/hostfile \
-         system/machines \
-      ;
-      do
-         if [ -r $hostfile ]; then
-            mpiopts="$mpiopts -hostfile $hostfile"
-            break
-         fi
-      done
-      ;;
-   esac
-
-#
-#   RUN IN PARALLEL
-#
-   if [ "$SCREEN" = no ] ; then
-      echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1"
-      $mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1 &
-   else
-      echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel | tee log"
-      $mpirun $mpiopts $APPLICATION $@ -parallel  | tee log
-   fi
 fi
 
 #------------------------------------------------------------------------------
