ENH: replace tutorials/AutoTest with bin/foamTestTutorial
- additional -serial/-parallel option:
  prefer Allrun-serial or Allrun-parallel if available

- optional -output=DIR to preserve output

ENH: report missing tutorials/ directory in RunFunctions

diff --git a/bin/foamTestTutorial b/bin/foamTestTutorial
--- a/bin/foamTestTutorial
+++ b/bin/foamTestTutorial
@@ -6,17 +6,18 @@
 #   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
-#     Copyright (C) 2020 OpenCFD Ltd.
+#     Copyright (C) 2020-2021 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
 #
 # Script
-#     tutorials/AutoTest dir [.. dirN]
+#     foamTestTutorial dir [.. dirN]
 #
 # Description
 #     Run foamRunTutorials with specified tutorial directories
-#     Creates/destroys a temporary directory for each test.
+#     Creates/destroys a temporary directory for each test unless
+#     an output directory has been specified.
 #
 # Environment
 #     Requires an initialized OpenFOAM environment.
@@ -35,13 +36,18 @@ printHelp() {
 usage: ${0##*/} [OPTION] dir [.. dirN]
 
 options:
-  -1            Modify case controlDict to run only one time step (default)
-  -full         Do not modify controlDict (run tutorial to completion)
-  -debian       Any modifications when running with autopkgtest
+  -1            Run only one time step (modifies controlDict) [default]
+  -full         Run to completion (does not modify controlDict)
+  -force        Force overwrite of existing output directories
+  -debian       Adjust for running with autopkgtest
+  -serial       Prefer Allrun-serial if available
+  -parallel     Prefer Allrun-parallel if available
+  -output=DIR   Output directory (default: a temporary directory)
   -help         Print the usage
 
-Run foamRunTutorials with specified tutorial directories.
-Creates/destroys a temporary directory for each.
+Run foamRunTutorials with specified tutorial directories
+Creates/destroys a temporary directory for each test unless
+an output directory has been specified.
 
 USAGE
     exit 0 # A clean exit
@@ -62,21 +68,22 @@ die()
 
 #------------------------------------------------------------------------------
 
-unset optDebian optVerbose
+unset optAllrun optDebian optForce optVerbose
+unset outputDir
 optRunLimit=1
 
 # Parse options
 while [ "$#" -gt 0 ]
 do
     case "$1" in
-    -h*)
-        printHelp
-        ;;
+    -h* | -help*)   printHelp ;;
 
+    -force)
+        optForce=true
+        ;;
     -1)
         optRunLimit="${1#-}"
         ;;
-
     -full)
         unset optRunLimit
         ;;
@@ -85,6 +92,14 @@ do
         # Redirect stderr to stdout, if autopkgtest (tests/control)
         # does NOT use "Restrictions: allow-stderr"
         exec 2>&1
+        ;;
+
+    -serial | -parallel)
+        optAllrun="Allrun-${1#-}"
+        ;;
+
+    -output=*)
+        outputDir="${1#*=}"
         ;;
 
     --)
@@ -109,8 +124,18 @@ done
 [ -n "$FOAM_TUTORIALS" ] || export FOAM_TUTORIALS="$WM_PROJECT_DIR"/tutorials
 
 [ -d "${WM_PROJECT_DIR:?}" ] || die "No OpenFOAM environment: $WM_PROJECT_DIR"
-[ -d "$FOAM_TUTORIALS" ] || die "No OpenFOAM tutorials : $FOAM_TUTORIALS"
+[ -d "$FOAM_TUTORIALS" ] || die "No OpenFOAM tutorials: $FOAM_TUTORIALS"
 
+
+#-------------------------------------------------------------------------------
+# Resolve the output directory
+if [ -n "$outputDir" ]
+then
+    outputDir="$(cd "$outputDir" 2>/dev/null && pwd -L)" || \
+        die "Cannot resolve output directory"
+
+    [ -w "$outputDir" ] || die "Output directory non-writable: $outputDir"
+fi
 
 #------------------------------------------------------------------------------
 
@@ -149,11 +174,29 @@ do
         echo "Run test: $testdir"
         set -e
 
-        TESTDIR="$(mktemp --directory --suffix=".$suffix")"
-        trap 'rm -rf $TESTDIR' 0 INT QUIT ABRT PIPE TERM
-
+        if [ -n "$outputDir" ]
+        then
+            TESTDIR="$outputDir/$suffix"
+            if [ -d "$TESTDIR" ]
+            then
+                if [ "$optForce" = true ]
+                then
+                    rm -rf "$TESTDIR"  # Remove old directory
+                else
+                    echo "Directory exists: $TESTDIR" 1>&2
+                    exit
+                fi
+            fi
+            mkdir "$TESTDIR"
+        else
+            TESTDIR="$(mktemp --directory --suffix=".$suffix")"
+            trap 'rm -rf $TESTDIR' 0 INT QUIT ABRT PIPE TERM
+        fi
         cp -r "$FOAM_TUTORIALS/$testdir"/* "$TESTDIR"/
-        cd "$TESTDIR"
+        cd "$TESTDIR" || exit
+
+        # In case the input already had results
+        foamCleanTutorials  > /dev/null 2>&1
 
         if [ -n "$optRunLimit" ]
         then
@@ -162,19 +205,26 @@ do
             set -e
         fi
 
-        nInput="$(ls | wc -l)"
-        foamRunTutorials
-        nOutput="$(ls | wc -l)"
+        nFilesBefore="$(ls | wc -l)"
 
-        if [ "$nInput" = 0 ]
+        if [ -n "$optAllrun" ] && [ -f ./"$optAllrun" ]
+        then
+            ./"$optAllrun"
+        else
+            foamRunTutorials
+        fi
+        nFilesAfter="$(ls | wc -l)"
+
+        if [ "$nFilesBefore" = 0 ]
         then
             echo "No input for $testdir" 1>&2
             exit 1
-        elif [ "$nOutput" = "$nInput" ]
+        elif [ "$nFilesBefore" = "$nFilesAfter" ]
         then
             echo "Run failure for $testdir" 1>&2
             exit 1
         else
+            # And/or grep for FatalError in log files
             echo "run: OK"
         fi
     ) && nPassed=$((nPassed + 1))
