TUT: adjust tutorials for test loop

diff --git a/tutorials/lagrangian/reactingParcelFoam/airRecirculationRoom/transient/Allrun b/tutorials/lagrangian/reactingParcelFoam/airRecirculationRoom/transient/Allrun
--- a/tutorials/lagrangian/reactingParcelFoam/airRecirculationRoom/transient/Allrun
+++ b/tutorials/lagrangian/reactingParcelFoam/airRecirculationRoom/transient/Allrun
@@ -3,14 +3,26 @@ cd "${0%/*}" || exit                                # Run from this directory
 . ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
 #------------------------------------------------------------------------------
 
-[[ -d constant/polyMesh ]] || rm -rf constant/polyMesh
+parent="../steady"
+latestTime=$(foamListTimes -case "$parent" -noZero -latestTime)
 
-cp -rf ../steady/constant/polyMesh constant
+if [ -z "$latestTime" ]
+then
+    echo "FatalError: no latestTime found for $PWD/$parent"
+    exit 1
+fi
+
+# Replace mesh unconditionally
+rm -rf constant/polyMesh
+cp -rf "$parent"/constant/polyMesh constant
 
 restore0Dir
 
-cp -f ../steady/500/U 0/
-cp -f ../steady/500/p 0/
+# Restart from steady
+cp -f \
+    "$parent/$latestTime"/U \
+    "$parent/$latestTime"/p \
+    0/
 
 runApplication $(getApplication)
 
