ENH: respect '-silent' option for cmake builds
- minor cleanup of wmake sources

diff --git a/wmake/scripts/makeFiles b/wmake/scripts/makeFiles
--- a/wmake/scripts/makeFiles
+++ b/wmake/scripts/makeFiles
@@ -31,6 +31,7 @@
 #     Usage : makeFiles
 #
 #------------------------------------------------------------------------------
+dirToString=$WM_DIR/platforms/$WM_ARCH$WM_COMPILER/dirToString
 
 if [ -r Make/files ]
 then
@@ -38,10 +39,15 @@ then
     exit 1
 fi
 
-dirToString=$WM_DIR/platforms/$WM_ARCH$WM_COMPILER/dirToString
+[ -x "$dirToString" ] || {
+    echo "Error: no command $dirToString" 1>&2
+    exit 1
+}
 
 [ -d Make ] || mkdir Make
 rm -f Make/files
+#------------------------------------------------------------------------------
+echo "Creating Make/files"
 
 for dir in $(find . -mindepth 1 -type d -print)
 do
@@ -53,7 +59,7 @@ do
         echo "$(echo $dir | $dirToString -strip)  =  ${dir#./}"
         ;;
     esac
-done >> Make/files
+done > Make/files
 [ -s Make/files ] && echo >> Make/files
 
 for file in $(find . -name "*.[cCylLfF]" -type f -print)
diff --git a/wmake/wmakeFilesAndOptions b/wmake/wmakeFilesAndOptions
--- a/wmake/wmakeFilesAndOptions
+++ b/wmake/wmakeFilesAndOptions
@@ -59,23 +59,23 @@ do
     -h | -help)   # Provide immediate help
         usage
         ;;
-    -*)
-        usage "unknown option: '$1'"
-        ;;
     *)
-        break
+        # No options/arguments
+        usage "unexpected options/arguments: $*"
         ;;
     esac
 done
 
-# No arguments
-[ "$#" -eq 0 ] || usage "unexpected arguments: '$*'"
-
+if [ -e Make ]
+then
+    echo "$Script error: Make directory already exists" 1>&2
+    exit 1
+fi
 
 #------------------------------------------------------------------------------
 # Check environment variables
 #------------------------------------------------------------------------------
-for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
+for check in WM_DIR WM_ARCH WM_COMPILER
 do
     eval test "\$$check" || {
         echo "$Script error: environment variable \$$check not set" 1>&2
@@ -83,24 +83,9 @@ do
     }
 done
 
-if [ -d Make ]
-then
-    echo "$Script error: Make directory already exists" 1>&2
-    exit 1
-else
-    mkdir Make
-fi
-
-[ -e Make/files ] || {
-    echo "$Script: Creating Make/files"
-    $WM_DIR/scripts/makeFiles
-}
-
-[ -e Make/options ] || {
-    echo "$Script: Creating Make/options"
-    $WM_DIR/scripts/makeOptions
-}
-
+mkdir Make
+[ -e Make/files ]   || $WM_DIR/scripts/makeFiles
+[ -e Make/options ] || $WM_DIR/scripts/makeOptions
 
 exit 0 # clean exit
 
