COMP: provide Allmake script for wmake tools
- convenient when bootstrapping some systems

diff --git a/wmake/scripts/wmakeFunctions b/wmake/scripts/wmakeFunctions
--- a/wmake/scripts/wmakeFunctions
+++ b/wmake/scripts/wmakeFunctions
@@ -30,7 +30,7 @@ checkEnv()
     for check in WM_PROJECT_DIR WM_OPTIONS WM_DIR
     do
         eval test "\$$check" || {
-            echo "$Script error: environment variable \$$check not set" 1>&2
+            echo "$Script error: Environment variable \$$check not set" 1>&2
             exit 1
         }
     done
diff --git a/wmake/wmakeFilesAndOptions b/wmake/wmakeFilesAndOptions
--- a/wmake/wmakeFilesAndOptions
+++ b/wmake/wmakeFilesAndOptions
@@ -26,7 +26,7 @@
 #     wmakeFilesAndOptions
 #
 # Usage
-#     wmakeFilesAndOptions
+#     wmakeFilesAndOptions [-help]
 #
 # Description
 #     Scan current directory for directories and source files
@@ -39,32 +39,28 @@ usage() {
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-Usage: $Script
+Usage: $Script [-help]
 
-    Scan current directory for directories and source files
-    and construct 'Make/files' and 'Make/options'
+Scans current directory for directories and source files and constructs
+the 'Make/files' and 'Make/options' files.
 
 USAGE
     exit 1
 }
 
-
-#------------------------------------------------------------------------------
-# Parse arguments and options
-#------------------------------------------------------------------------------
-
-while [ "$#" -gt 0 ]
+# Find -help anywhere
+for i
 do
-    case "$1" in
-    -h | -help*)   # Provide immediate help
-        usage
-        ;;
-    *)
-        # No options/arguments
-        usage "unexpected options/arguments: $*"
-        ;;
-    esac
+    case "$i" in (-h | -help*) usage ;; esac
 done
+
+#------------------------------------------------------------------------------
+
+# No options/arguments
+[ "$#" -eq 0 ] || {
+    echo "$Script error: Unexpected options/arguments: $*" 1>&2
+    exit 1
+}
 
 if [ -e Make ]
 then
@@ -72,20 +68,9 @@ then
     exit 1
 fi
 
-#------------------------------------------------------------------------------
-# Check environment variables
-#------------------------------------------------------------------------------
-for check in WM_DIR WM_ARCH WM_COMPILER
-do
-    eval test "\$$check" || {
-        echo "$Script error: environment variable \$$check not set" 1>&2
-        exit 1
-    }
-done
-
 mkdir Make
-[ -e Make/files ]   || $WM_DIR/scripts/makeFiles
-[ -e Make/options ] || $WM_DIR/scripts/makeOptions
+[ -e Make/files ]   || "${0%/*}"/scripts/makeFiles
+[ -e Make/options ] || "${0%/*}"/scripts/makeOptions
 
 exit 0 # clean exit
 
