consistency update: foamNew, foamNewSource, foamNewTemplate
- simplified the logic
- provide direct link to the respective scripts
- provide help from the respective scripts

diff --git a/bin/templates/source/foamNewSource b/bin/templates/source/foamNewSource
--- a/bin/templates/source/foamNewSource
+++ b/bin/templates/source/foamNewSource
@@ -24,18 +24,18 @@
 #     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Script
-#     foamNew
+#     foamNewSource
 #
 # Description
 #     Create a new standard OpenFOAM source file
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
+Template="$WM_PROJECT_DIR/bin/templates/source/_Template"
 
 usage() {
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
-
 usage: $Script <type> <class name>
 
 * create a new standard OpenFOAM source file
@@ -46,49 +46,56 @@ USAGE
     exit 1
 }
 
-if [ "$#" -ne 2 ]; then
-   usage "wrong number of arguments, expected 2"
-fi
 
-unset suffix fileType
+# this implicitly covers a lone -help
+[ "$#" -gt 1 ] || usage
+
+className="$2"
+unset subType Type
+
 case "$1" in
+-h | -help)
+    usage
+    ;;
 C|H)
-   template=foamTemplate
-   fileType=$1
-   ;;
+    Type=".$1"
+    ;;
 I)
-   suffix=$1
-   template=foamTemplateI
-   fileType=H
-   ;;
+    Type="$1.H"
+    ;;
 IO)
-   suffix=$1
-   template=foamTemplateIO
-   fileType=C
-   ;;
+    Type="$1.C"
+    ;;
 app|App)
-   template=foamAppTemplate
-   fileType=C
-   if [ ! -d Make ]; then
-       echo "foamNew: Creating Make/files and Make/options"
-       wmakeFilesAndOptions
-   fi
-   ;;
+    subType=App
+    Type=".C"
+    ;;
 *)
-   usage "unknown type"
-   ;;
+    usage "unknown type"
+    ;;
 esac
+[ "$#" -eq 2 ] || usage "wrong number of arguments"
+shift 2
 
 
-fileName=$2$suffix.$fileType
+fileName="$className$Type"
 
-if [ -e "$fileName" ]; then
-   echo "Cannot make $fileName, file exists"
-   exit 1
+
+echo "$Script: Creating new interface file $fileName"
+if [ -e "$fileName" ]
+then
+    echo "   Error: file exists"
+    exit 1
 fi
 
-echo $Script: Creating new interface file $fileName
-sed s/className/$2/g \
-    $WM_PROJECT_DIR/bin/foamTemplates/source/$template.$fileType > $fileName
+
+# process class name
+sed "s/CLASSNAME/$className/g" $Template$subType$Type > $fileName
+
+
+if [ "$subType" = App -a ! -d Make ]
+then
+    wmakeFilesAndOptions
+fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/templates/sourceTemplate/foamNewTemplate b/bin/templates/sourceTemplate/foamNewTemplate
--- a/bin/templates/sourceTemplate/foamNewTemplate
+++ b/bin/templates/sourceTemplate/foamNewTemplate
@@ -24,13 +24,14 @@
 #     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Script
-#     newSourceTemplate
+#     foamNewTemplate
 #
 # Description
 #     Create a new standard OpenFOAM templated source file
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
+Template="$WM_PROJECT_DIR/bin/templates/sourceTemplate/_TemplateTemplate"
 
 usage() {
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
@@ -46,51 +47,50 @@ USAGE
     exit 1
 }
 
-if [ "$#" -le 2 ]; then
-   usage "wrong number of arguments, expected 3 (or more)"
-fi
+# this implicitly covers a lone -help
+[ "$#" -gt 1 ] || usage
 
-unset suffix fileType
+
+className="$2"
+unset Type
+
 case "$1" in
+-h | -help)
+    usage
+    ;;
 C|H)
-   Template=Template
-   fileType=$1
-   className=$2
-   ;;
+    Type=".$1"
+    ;;
 I)
-   suffix=$1
-   Template=TemplateI
-   fileType=H
-   className=$2
-   ;;
+    Type="$1.H"
+    ;;
 IO)
-   suffix=$1
-   Template=TemplateIO
-   fileType=C
-   className=$2
-   ;;
+    Type="$1.C"
+    ;;
 *)
-   usage "unknown type"
-   ;;
+    usage "unknown type"
+    ;;
 esac
+[ "$#" -ge 3 ] || usage "wrong number of arguments"
+shift 2
+
+fileName="$className$Type"
 
 
-fileName=$className$suffix.$fileType
-
-if [ -e "$fileName" ]; then
-   echo "Cannot make $fileName, file exists"
-   exit 1
+echo "$Script: Creating new template interface file $fileName"
+if [ -e "$fileName" ]
+then
+    echo "   Error: file exists"
+    exit 1
 fi
 
-shift 2
-echo "$Script: Creating new interface file $fileName"
 
 # process class name
-sed -e "s/ClassName/$className/g" \
-    $WM_PROJECT_DIR/bin/foamTemplates/sourceTemplate/foamTemplate$Template.$fileType > $fileName.1
+sed -e "s/CLASSNAME/$className/g" $Template$Type > $fileName.1
+
 
 # process template arguments
-for tArg in $*
+for tArg
 do
     sed -e "s/TemplateClassArgument/class $tArg, TemplateClassArgument/g" \
         -e "s/TemplateArgument/$tArg, TemplateArgument/g" \
@@ -99,7 +99,8 @@ do
     mv $fileName.2 $fileName.1
 done
 
-# remove remaining ", Template argument"
+
+# remove remaining ", Template .."
 sed -e "s/, TemplateClassArgument//g" \
     -e "s/, TemplateArgument//g" \
     $fileName.1 > $fileName
