ENH: update handling of versioning and make control (issue #1010)
- Use the OPENFOAM define (eg, 1806, 1812), which normally corresponds
  to a major release, to define an API level. This remains consistent
  within a release cycle and means that it is possible to manage
  several sub-versions and continue to have a consistent lookup.

  The current API value is updated automatically during the build
  and cached as meta data for later use, even when the wmake/ directory
  is missing or OpenFOAM has not yet be initialized.

  The version information reported on program start or with -help
  usage adjusted to reflect this. The build tag from git now also
  carries the date as being more meaningful to trace than a hash
  value.

- Update etc/bashrc and etc/cshrc to obtain the project directory
  directly instead of via its prefix directory. The value obtained
  corresponds to an absolute path, from which the prefix directory
  can be obtained.

  The combination of these changes removes the reliance on any
  particular directory naming convention.
  For example,

     With an 1812 version (API level):

     WM_PROJECT_VERSION=myVersion

     installed as /some/path/somewhere/openfoam-mySandbox

  This makes the -prefix, -foamInstall, -projectVersion, -version
  values of foamEtcFiles, and similar entries for foamConfigurePaths
  superfluous.

  WM_PROJECT_INST_DIR is no longer required or used

ENH: improve handling and discovery of ThirdParty

- improve the flexibility and reusability of ThirdParty packs to cover
  various standard use cases:

    1. Unpacking initial release tar files with two parallel directories
       - OpenFOAM-v1812/
       - ThirdParty-v1812/

    2. With an adjusted OpenFOAM directory name, for whatever reason
       - OpenFOAM-v1812-myCustom/
       - openfoam-1812-other-info/

    3. Operating with/without ThirdParty directory

  To handle these use cases, the following discovery is used.

  Note PROJECT = the OpenFOAM directory `$WM_PROJECT_DIR`
       PREFIX = the parent directory
       VERSION = `$WM_PROJECT_VERSION`
       API = `$WM_PROJECT_API`, as per `foamEtcFiles -show-api`

   0. PROJECT/ThirdParty
      - for single-directory installations

   1. PREFIX/ThirdParty-VERSION
      - this corresponds to the traditional approach

   2. PREFIX/ThirdParty-vAPI
      - allows for an updated value of VERSION (eg, v1812-myCustom)
        without requiring a renamed ThirdParty. The API value
        would still be '1812' and the original ThirdParty-v1812/
        would be found.

   3. PREFIX/ThirdParty-API
      - this is the same as the previous example, but using an unadorned
        API value. This also makes sense if the chosen version name also
        uses the unadorned API value in its naming
        (eg, 1812-patch190131, 1812.19W03)

   4. PREFIX/ThirdParty-common
      - permits maximum reuse for various versions, but only for
        experienced user who are aware of potential version
        incompatibilities

   Directory existence is checked as is the presence of an Allwmake file
   or a platforms/ directory. This reduces the potential of false positive
   matches and limits the selection to directories that are either
   with sources (has the Allwmake file), or pre-compiled binaries (has
   the platforms/ directory).

   If none of the explored directories are found to be suitable,
   it reverts to using a PROJECT/ThirdParty dummy location since
   this is within the project source tree and can be trusted to
   have no negative side-effects.

ENH: add csh support to foamConfigurePaths

- this removes the previously experienced inconsistence in config file
  contents.

REMOVED: foamExec

- was previously used when switching versions and before the
  bashrc/cshrc discovery logic was added. It is now obsolete.

diff --git a/etc/cshrc b/etc/cshrc
--- a/etc/cshrc
+++ b/etc/cshrc
@@ -22,10 +22,10 @@
 #         -  $WM_PROJECT_DIR/etc/prefs.csh
 #
 #       - User or group values (first file found):
-#         -  ~/.OpenFOAM/$WM_PROJECT_VERSION/prefs.csh
+#         -  ~/.OpenFOAM/$WM_PROJECT_API/prefs.csh
 #         -  ~/.OpenFOAM/prefs.csh
-#         -  $WM_PROJECT_SITE/$WM_PROJECT_VERSION/etc/prefs.csh
-#         -  $WM_PROJECT_SITE/etc/prefs.csh
+#         -  $WM_PROJECT_SITE/$WM_PROJECT_API/etc/prefs.csh
+#         -  $WM_PROJECT_SITE/prefs.csh
 #
 # Environment
 #     FOAM_VERBOSE (set/unset)
@@ -43,17 +43,22 @@
 setenv WM_PROJECT OpenFOAM
 setenv WM_PROJECT_VERSION plus
 
-# [FOAM_INST_DIR] - parent directory containing the OpenFOAM installation.
+# [projectDir] - parent directory containing the OpenFOAM installation.
 # \- When this file is located as $WM_PROJECT_DIR/etc/cshrc, the next lines
 #    should work when sourced by CSH or TCSH shells. If this however fails,
 #    set one of the fallback values to an appropriate path.
-# --
-set FOAM_INST_DIR=`lsof +p $$ |& \
-    sed -n -e 's@[^/]*@@' -e 's@/'$WM_PROJECT'[^/]*/etc/cshrc.*@@p'`
-# set FOAM_INST_DIR=$HOME/$WM_PROJECT
-# set FOAM_INST_DIR=/opt/$WM_PROJECT
-# set FOAM_INST_DIR=/usr/local/$WM_PROJECT
 #
+#    This can be removed if an absolute path is provided for WM_PROJECT_DIR
+#    later on in this file.
+# --
+# If the directory naming does not match WM_PROJECT, need to change here
+set projectName="$WM_PROJECT"
+set projectDir=`lsof +p $$ |& \
+    sed -n -e 's@^[^/]*@@; s@\(/'"$projectName"'[^/]*\)/etc/cshrc[^/]*@\1@p'`
+
+# set projectDir="$HOME/OpenFOAM/OpenFOAM-$WM_PROJECT_VERSION"
+# set projectDir="/opt/OpenFOAM/OpenFOAM-$WM_PROJECT_VERSION"
+# set projectDir="/usr/local/OpenFOAM/OpenFOAM-$WM_PROJECT_VERSION"
 # END OF (NORMAL) USER EDITABLE PART
 ################################################################################
 
@@ -138,10 +143,8 @@ if ( $?FOAM_SITE_LIBBIN ) then
    set foamOldDirs="$foamOldDirs $FOAM_SITE_LIBBIN"
 endif
 
-# Location of installation and third-party software
-setenv WM_PROJECT_INST_DIR $FOAM_INST_DIR
-setenv WM_PROJECT_DIR      $WM_PROJECT_INST_DIR/$WM_PROJECT-$WM_PROJECT_VERSION
-setenv WM_THIRD_PARTY_DIR  $WM_PROJECT_INST_DIR/ThirdParty-$WM_PROJECT_VERSION
+# [WM_PROJECT_DIR] - Location of this OpenFOAM version
+setenv WM_PROJECT_DIR "$projectDir"
 
 # [WM_PROJECT_USER_DIR] - Location of user files
 setenv WM_PROJECT_USER_DIR "$HOME/$WM_PROJECT/$LOGNAME-$WM_PROJECT_VERSION"
@@ -157,118 +160,17 @@ else
     unsetenv WM_PROJECT_SITE
 endif
 
-# Load shell "functions" (actually aliases)
-source $WM_PROJECT_DIR/etc/config.csh/functions
 
-# Overrides via <prefs.csh>
-# 1. other (system) values
-_foamEtc -mode=o prefs.csh
-
-# 2. user or group values (unless disabled)
-if (! $?FOAM_CONFIG_NOUSER ) then
-    _foamEtc -mode=ug prefs.csh
+# Finalize setup of OpenFOAM environment
+if ( -d "$WM_PROJECT_DIR" ) then
+    if ($?FOAM_VERBOSE && $?prompt) echo "source $WM_PROJECT_DIR/etc/config.csh/setup"
+    source "$WM_PROJECT_DIR/etc/config.csh/setup" "${*}"
+else
+    echo "Error: did not locate installation path for $WM_PROJECT-$WM_PROJECT_VERSION"
+    echo "No directory: $WM_PROJECT_DIR"
 endif
 
-# Evaluate command-line parameters and record settings for later.
-# These can be used to set/unset values, specify additional files etc.
-setenv FOAM_SETTINGS "${*}"
-while ( $#argv > 0 )
-    switch ($argv[1])
-    case -*:
-        # Stray option (not meant for us here) -> get out
-        break
-        breaksw
-    case *=:
-        # name=       -> unsetenv name
-        if ($?FOAM_VERBOSE && $?prompt) echo "unsetenv $argv[1]:s/=//"
-        eval "unsetenv $argv[1]:s/=//"
-        breaksw
-    case *=*:
-        # name=value  -> setenv name value
-        if ($?FOAM_VERBOSE && $?prompt) echo "setenv $argv[1]:s/=/ /"
-        eval "setenv $argv[1]:s/=/ /"
-        breaksw
-    default:
-        # Filename: source it
-        if ( -f "$argv[1]" ) then
-            if ($?FOAM_VERBOSE && $?prompt) echo "Using: $argv[1]"
-            source "$argv[1]"
-        else
-            _foamEtc -silent "$argv[1]"
-        endif
-        breaksw
-    endsw
-    shift
-end
-
-
-# Clean standard environment variables (PATH, MANPATH, LD_LIBRARY_PATH)
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Prevent local variables from shadowing setenv variables
-unset PATH MANPATH LD_LIBRARY_PATH LD_PRELOAD
-if (! $?LD_LIBRARY_PATH ) setenv LD_LIBRARY_PATH
-if (! $?MANPATH ) setenv MANPATH
-
-_foamClean PATH "$foamOldDirs"
-_foamClean MANPATH "$foamOldDirs"
-_foamClean LD_LIBRARY_PATH "$foamOldDirs"
-
-# Setup for OpenFOAM compilation etc
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-_foamEtc -config  settings
-
-# Setup for third-party packages
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-_foamEtc -config  mpi
-_foamEtc -config  paraview -- "$FOAM_SETTINGS"  # Pass through for evaluation
-_foamEtc -config  vtk
-_foamEtc -config  ensight
-## _foamEtc -config  ADIOS
-## _foamEtc -config  ADIOS2
-_foamEtc -config  CGAL
-_foamEtc -config  FFTW
-
-if ( -d "$WM_PROJECT_DIR/doc/man1" ) then
-    _foamAddMan "$WM_PROJECT_DIR/doc"
-endif
-
-# Interactive shell
-if ($?prompt) then
-    _foamEtc -config  aliases
-    _foamEtc -config  tcsh_completion
-endif
-
-
-# Clean environment paths again. Only remove duplicates
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-
-_foamClean PATH
-_foamClean MANPATH
-_foamClean LD_LIBRARY_PATH
-
-# Add trailing ':' for system manpages
-if ( $?MANPATH ) then
-    setenv MANPATH "${MANPATH}:"
-endif
-
-if ( $?LD_PRELOAD ) then
-    _foamClean LD_PRELOAD
-endif
-
-
-# Cleanup temporary information
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-
-# Unload shell "functions"
-unalias _foamClean
-unalias _foamEtc
-unalias _foamAddPath
-unalias _foamAddMan
-unalias _foamAddLib
-unalias _foamAddLibAuto
-
-# Variables (done as the last statement for a clean exit code)
-unset FOAM_INST_DIR     # Old variable name (OpenFOAM-v1606) - now unneeded
-unset cleaned foamOldDirs
+# Cleanup variables (done as final statement for a clean exit code)
+unset foamOldDirs projectDir projectName
 
 #------------------------------------------------------------------------------
