TUT: simplify setups.orig cases
DOC: Curle: fix typo in header file (fixes #2498)

TUT: airfoil2D: apply standard freestream conditions for nuTilda and nut

diff --git a/tutorials/incompressible/boundaryFoam/steadyBoundaryLayer/Allrun b/tutorials/incompressible/boundaryFoam/steadyBoundaryLayer/Allrun
--- a/tutorials/incompressible/boundaryFoam/steadyBoundaryLayer/Allrun
+++ b/tutorials/incompressible/boundaryFoam/steadyBoundaryLayer/Allrun
@@ -1,16 +1,27 @@
 #!/bin/sh
 cd "${0%/*}" || exit                                # Run from this directory
 . ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
-. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
 #------------------------------------------------------------------------------
 
-# setups
+# settings
 
     # operand setups
     setups="
     kEpsilon-nutkWallFunction
     LaunderSharmaKE-nutkWallFunction
     "
+
+    # flag to enable computations
+    run=true
+
+    # flag to enable computations in parallel mode
+    parallel=false
+
+    # flag to enable to use a common mesh
+    common_mesh=true
+
+    # flag to enable to use a common dynamic code
+    common_dynamic_code=true
 
     # operand exponents of kinematic viscosity values
     nuExponents="2 3 4 5 6 7 8"
@@ -19,107 +30,163 @@ cd "${0%/*}" || exit                                # Run from this directory
 #------------------------------------------------------------------------------
 
 #######################################
-# Collect results into a given path
-# and clean the case for the next run
+# Create the given setup
 # Arguments:
-#    $1 = Path to move results
+#    $1 = Path to create the setup
 # Outputs:
 #    Writes info to stdout
 #######################################
-collect() {
+dry_run_setup() {
 
-    [ $# -eq 0 ] && { echo "Usage: $0 dir-model"; exit 1; }
+    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }
 
-    collection="$1"
+    setup="$1"
+    exponent="$2"
+    dirSetup="setups/$setup/$exponent"
+    dirSetupOrig="setups.orig/$setup"
+    dirOrig="$dirSetupOrig/0.orig"
+    dirConstant="$dirSetupOrig/constant"
+    dirSystem="$dirSetupOrig/system"
 
-    dirResult=results/"$collection"
-    dirSettings="$dirResult"/settings
+    printf "\n# Create the setup: %s %s\n" "$setup" nu=1e-"$exponent"
+
+    if [ ! -d "$dirSetup" ]
+    then
+        mkdir -p "$dirSetup"
+
+        cp -aRfL "setups.orig/common/." "$dirSetup"
+        cp -afL "$dirSetupOrig"/All* "$dirSetup" 2>/dev/null || :
+        [ -d "$dirOrig" ] && cp -aRfL "$dirOrig/." "$dirSetup/0.orig"
+        [ -d "$dirConstant" ] && cp -aRfL "$dirConstant/." "$dirSetup/constant"
+        [ -d "$dirSystem" ] && cp -aRfL "$dirSystem/." "$dirSetup/system"
+    else
+        printf "\n      # Directory %s already exists\n" "$dirSetup"
+        printf "      # Skipping the creation of a new setup\n"
+    fi
+}
+
+
+#######################################
+# Run the given setup
+# Arguments:
+#    $1 = Path to the setup to run
+# Outputs:
+#    Writes info to stdout
+#######################################
+run_setup() {
+
+    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }
+
+    setup="$1"
+    exponent="$2"
+    dirSetup="setups/$setup/$exponent"
+    dirResult="results/$setup/$exponent"
+
+    dry_run_setup "$setup" "$exponent"
+    [ -d results ] || mkdir -p results
+    [ -d results/"$setup" ] || mkdir -p results/"$setup"
+
+    printf "\n# Run the setup: %s %s\n\n" "$setup" nu=1e-"$exponent"
 
     if [ ! -d "$dirResult" ]
     then
+        cp -Rf "$dirSetup" "$dirResult"
 
-        echo "      # Collecting results and settings into $dirResult"
+        if [ "$common_mesh" = true ]
+        then
+            if [ -d results/mesh ]
+            then
+                printf "## Copy the common mesh to the setup: %s\n\n" "$setup"
+                cp -Rf results/mesh/polyMesh "$dirResult"/constant/.
+            fi
+        fi
 
-        mkdir -p "$dirResult"
-        mkdir -p "$dirSettings"
+        if [ "$common_dynamic_code" = true ]
+        then
+            if [ -d results/dynamicCode ]
+            then
+                printf "## Copy the common dynamic code to the setup: %s\n\n" "$setup"
+                cp -Rf results/dynamicCode "$dirResult"/.
+            fi
+        fi
 
-        mv -f $(foamListTimes) "$dirResult"
-        [ -d postProcessing ] && mv -f postProcessing "$dirResult"
-        mv -f log.* "$dirResult"
-        mv -f graphs/ "$dirResult"
-        mv -f logs/ "$dirResult"
-        cp -f system/{fv*,controlDict} constant/*Properties "$dirSettings"
-        mv -f 0/ "$dirSettings"
 
-        echo "      # Cleaning up the case"
+        if [ "$parallel" = true ]
+        then
+            ( cd "$dirResult" && ./Allrun-parallel )
+        else
+            ( cd "$dirResult" && ./Allrun )
+        fi
 
-        cleanTimeDirectories
-        cleanAuxiliary
-        cleanPostProcessing
+
+        if [ "$common_mesh" = true ]
+        then
+            if [ ! -d results/mesh ]
+            then
+                printf "\n## Store the mesh of %s as the common mesh\n\n" "$setup"
+                mkdir -p results/mesh
+                cp -Rf "$dirResult"/constant/polyMesh results/mesh/.
+            fi
+        fi
+
+        if [ "$common_dynamic_code" = true ]
+        then
+            if [ ! -d results/dynamicCode ] && [ -d "$dirResult"/dynamicCode ]
+            then
+                printf "\n## Store the dynamic code of %s as the common dynamic code\n\n" "$setup"
+                cp -Rf "$dirResult"/dynamicCode results/.
+            fi
+        fi
+
 
     else
-
-        echo "      # Directory $dirResult already exists"
-        echo "      # Skipping the computation"
-
+        printf "      # Directory %s already exists\n" "$dirResult"
+        printf "      # Skipping the computation of the given setup\n"
     fi
-
 }
 
 
 #------------------------------------------------------------------------------
 
-for setup in $setups
+[ "$parallel" = true ] && {
+    echo "boundaryFoam has no parallel option - skipping the execution" 1>&2
+    exit 1
+}
+
+
+#------------------------------------------------------------------------------
+
+for exponent in $nuExponents
 do
+    sed "s|EXPONENT|$exponent|g" \
+        setups.orig/common/constant/transportProperties.template > \
+        setups.orig/common/constant/transportProperties
 
-    echo ""
-    echo "# Computations for the setup: $setup"
-    echo ""
-
-    dirSetup="setups.orig/$setup"
-    cp -rfL "$dirSetup/0.orig" .
-    cp -rfL "$dirSetup/constant" .
-    cp -rfL "$dirSetup/system" .
-    cp -rf 0.orig/ 0/
-
-    if [ ! -d constant/polyMesh ]
-    then
-        runApplication blockMesh
-        runApplication renumberMesh -overwrite -constant
-        runApplication checkMesh -allTopology -allGeometry -constant
-    fi
-
-    echo "# yPlus vs uPlus" > yPlus_vs_uPlus.xy
-
-    for exponent in $nuExponents
+    for setup in $setups
     do
+        dirSetupOrig="setups.orig/$setup"
 
-        echo "    Setting nu to 1e-$exponent"
-
-        sed "s|EXPONENT|$exponent|g" constant/transportProperties.template \
-            > constant/transportProperties
-
-        [ -d 0 ] || restore0Dir
-
-        runApplication $(getApplication)
-
-        runApplication foamLog log.boundaryFoam
-
-        if [ -e logs/yPlus_0 ]
+        if [ ! -d "$dirSetupOrig" ]
         then
-            yPlus=$(awk < logs/yPlus_0 'END{print $2}')
-            uPlus=$(awk < logs/uPlus_0 'END{print $2}')
-
-            echo "$yPlus $uPlus" >> yPlus_vs_uPlus.xy
+            echo "Setup directory: $dirSetupOrig" \
+                "could not be found - skipping execution" 1>&2
+            continue
         fi
 
-        collect "$setup/$exponent"
-
+        if [ "$run" = true ]
+        then
+            run_setup "$setup" "$exponent"
+        else
+            dry_run_setup "$setup" "$exponent"
+        fi
     done
-
-    mv -f yPlus_vs_uPlus.xy results/"$setup"/
-
 done
+
+
+if notTest "$@" && [ "$run" = true ]
+then
+    ./plot
+fi
 
 
 #------------------------------------------------------------------------------
diff --git a/tutorials/incompressible/pimpleFoam/laminar/planarPoiseuille/plot b/tutorials/incompressible/pimpleFoam/laminar/planarPoiseuille/plot
--- a/tutorials/incompressible/pimpleFoam/laminar/planarPoiseuille/plot
+++ b/tutorials/incompressible/pimpleFoam/laminar/planarPoiseuille/plot
@@ -14,35 +14,19 @@ cd "${0%/*}" || exit                                # Run from this directory
 
 #------------------------------------------------------------------------------
 
-# Requires gnuplot
-command -v gnuplot >/dev/null || {
-    echo "FOAM FATAL ERROR: gnuplot not found - skipping graph creation" 1>&2
-    exit 1
-}
-
-# Check "results" directory
-[ -d "results" ] || {
-    echo "FOAM FATAL ERROR: No results directory found - skipping graph creation" 1>&2
-    exit 1
-}
-
-
-#------------------------------------------------------------------------------
-
 plot_t_vs_Ux() {
 
     setups=$@
 
-    benchmarkFile="WatersKing.dat"
-
     n=0
     for setup in $setups
     do
+        benchmarkFile="results/$setup/WatersKing.dat"
         sampleFiles[$n]="results/$setup/postProcessing/probes/0/Unp"
         n=$(($n+1))
     done
 
-    endTime=$(foamDictionary system/controlDict -entry endTime -value)
+    endTime=$(foamDictionary results/$setup/system/controlDict -entry endTime -value)
     image="plots/planarPoiseuille.png"
 
     gnuplot<<PLT
@@ -67,6 +51,21 @@ plot_t_vs_Ux() {
         for [i=1:words(samples)] word(samples, i) t word(names, i) \
             w linespoints pointinterval 100 lt i pt 6 ps 1.5
 PLT
+}
+
+
+#------------------------------------------------------------------------------
+
+# Requires gnuplot
+command -v gnuplot >/dev/null || {
+    echo "gnuplot not found - skipping graph creation" 1>&2
+    exit 1
+}
+
+# Check "results" directory
+[ -d "results" ] || {
+    echo "No results directory found - skipping graph creation" 1>&2
+    exit 1
 }
 
 
diff --git a/tutorials/incompressible/simpleFoam/bump2D/Allrun b/tutorials/incompressible/simpleFoam/bump2D/Allrun
--- a/tutorials/incompressible/simpleFoam/bump2D/Allrun
+++ b/tutorials/incompressible/simpleFoam/bump2D/Allrun
@@ -1,7 +1,6 @@
 #!/bin/sh
 cd "${0%/*}" || exit                                # Run from this directory
 . ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
-. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
 #------------------------------------------------------------------------------
 
 # settings
@@ -13,106 +12,132 @@ cd "${0%/*}" || exit                                # Run from this directory
     kEpsilonPhitF
     "
 
+    # flag to enable computations
+    run=true
+
     # flag to enable computations in parallel mode
     parallel=true
+
+    # flag to enable to use a common mesh
+    common_mesh=true
+
+    # flag to enable to use a common dynamic code
+    common_dynamic_code=true
 
 
 #------------------------------------------------------------------------------
 
 #######################################
-# Extract a value (Eg, from boundaryField/bump/value)
+# Create the given setup
 # Arguments:
-#    $1 = dictEntry
-#    $2 = inputFile
-#    $3 = outputFile
+#    $1 = Path to create the setup
 # Outputs:
-#    Writes to 'outputFile'
-# Notes:
-#    Only retains values between, but not including the ( ) delimiters.
-#    For example,
-#----
-#    value           nonuniform List<scalar>
-#    110
-#    (
-#    0.0041520092
-#    0.012577691
-#    0.021250264
-#    0.030176962
-#    )
-#    ;
+#    Writes info to stdout
 #######################################
-extractVal()
-{
-    if [ -f "$2" ]
+dry_run_setup() {
+
+    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }
+
+    setup="$1"
+    dirSetup="setups/$setup"
+    dirSetupOrig="setups.orig/$setup"
+    dirOrig="$dirSetupOrig/0.orig"
+    dirConstant="$dirSetupOrig/constant"
+    dirSystem="$dirSetupOrig/system"
+
+    printf "\n# Create the setup: %s\n" "$setup"
+
+    if [ ! -d "$dirSetup" ]
     then
-        foamDictionary -entry "$1" -value "$2" | \
-            sed -n '/(/,/)/{ s/[()]//g; /^ *$/d; p}' \
-            > "$3"
+        mkdir -p "$dirSetup"
+
+        cp -aRfL "setups.orig/common/." "$dirSetup"
+        cp -afL "$dirSetupOrig"/All* "$dirSetup" 2>/dev/null || :
+        [ -d "$dirOrig" ] && cp -aRfL "$dirOrig/." "$dirSetup/0.orig"
+        [ -d "$dirConstant" ] && cp -aRfL "$dirConstant/." "$dirSetup/constant"
+        [ -d "$dirSystem" ] && cp -aRfL "$dirSystem/." "$dirSetup/system"
     else
-        # Or some other tag?
-        echo "Not such file: $2" 1>&2
-        echo "0" > "$3"
+        printf "\n      # Directory %s already exists\n" "$dirSetup"
+        printf "      # Skipping the creation of a new setup\n"
     fi
 }
 
 
 #######################################
-# Collect results into a given path
-# and clean the case for the next run
+# Run the given setup
 # Arguments:
-#    $1 = Path to move results
+#    $1 = Path to the setup to run
 # Outputs:
 #    Writes info to stdout
 #######################################
-collect() {
+run_setup() {
 
-    [ $# -eq 0 ] && { echo "Usage: $0 dir-model"; exit 1; }
+    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }
 
-    collection="$1"
+    setup="$1"
+    dirSetup="setups/$setup"
+    dirResult="results/$setup"
 
-    dirResult=results/"$collection"
-    dirSettings="$dirResult"/settings
+    dry_run_setup "$setup"
+    [ -d results ] || mkdir -p results
+
+    printf "\n# Run the setup: %s\n\n" "$setup"
 
     if [ ! -d "$dirResult" ]
     then
+        cp -Rf "$dirSetup" "$dirResult"
 
-        echo "      # Collecting results and settings into $dirResult"
+        if [ "$common_mesh" = true ]
+        then
+            if [ -d results/mesh ]
+            then
+                printf "## Copy the common mesh to the setup: %s\n\n" "$setup"
+                cp -Rf results/mesh/polyMesh "$dirResult"/constant/.
+            fi
+        fi
 
-        mkdir -p "$dirResult"
-        mkdir -p "$dirSettings"
+        if [ "$common_dynamic_code" = true ]
+        then
+            if [ -d results/dynamicCode ]
+            then
+                printf "## Copy the common dynamic code to the setup: %s\n\n" "$setup"
+                cp -Rf results/dynamicCode "$dirResult"/.
+            fi
+        fi
 
-        endTime=$(foamListTimes -latestTime)
 
-        # Create datasets for benchmark comparisons
-        extractVal boundaryField.bump.value "$endTime/Cx" Cx.$$
-        extractVal boundaryField.bump.value "$endTime/wallShearStress" tau.$$
-        extractVal boundaryField.bump.value "$endTime/Cp" cp.$$
+        if [ "$parallel" = true ]
+        then
+            ( cd "$dirResult" && ./Allrun-parallel )
+        else
+            ( cd "$dirResult" && ./Allrun )
+        fi
 
-        echo "# ccx tau_xx tau_yy tau_zz cp" > profiles.dat
-        paste -d ' ' Cx.$$ tau.$$ cp.$$ >> profiles.dat
-        rm -f Cx.$$ tau.$$ cp.$$
 
-        mv -f $(foamListTimes) "$dirResult"
-        [ -d postProcessing ] && mv -f postProcessing "$dirResult"
-        [ -d processor0 ] && mv -f processor* "$dirResult"
-        mv -f log.* "$dirResult"
-        mv -f profiles.dat "$dirResult"
-        cp -f system/{fv*,controlDict} constant/*Properties "$dirSettings"
-        mv -f 0/ "$dirSettings"
+        if [ "$common_mesh" = true ]
+        then
+            if [ ! -d results/mesh ]
+            then
+                printf "\n## Store the mesh of %s as the common mesh\n\n" "$setup"
+                mkdir -p results/mesh
+                cp -Rf "$dirResult"/constant/polyMesh results/mesh/.
+            fi
+        fi
 
-        echo "      # Cleaning up the case"
+        if [ "$common_dynamic_code" = true ]
+        then
+            if [ ! -d results/dynamicCode ] && [ -d "$dirResult"/dynamicCode ]
+            then
+                printf "\n## Store the dynamic code of %s as the common dynamic code\n\n" "$setup"
+                cp -Rf "$dirResult"/dynamicCode results/.
+            fi
+        fi
 
-        cleanTimeDirectories
-        cleanAuxiliary
-        cleanPostProcessing
 
     else
-
-        echo "      # Directory $dirResult already exists"
-        echo "      # Skipping the computation"
-
+        printf "      # Directory %s already exists\n" "$dirResult"
+        printf "      # Skipping the computation of the given setup\n"
     fi
-
 }
 
 
@@ -120,58 +145,28 @@ collect() {
 
 for setup in $setups
 do
+    dirSetupOrig="setups.orig/$setup"
 
-    echo ""
-    echo "# Computations for the setup: $setup"
-    echo ""
-
-    dirSetup="setups.orig/$setup"
-
-    if [ ! -d "$dirSetup" ]
+    if [ ! -d "$dirSetupOrig" ]
     then
-        echo "Setup directory: $dirSetup" \
+        echo "Setup directory: $dirSetupOrig" \
              "could not be found - skipping execution" 1>&2
-        exit 1
+        continue
     fi
 
-    cp -rfL "$dirSetup/0.orig" .
-    cp -rfL "$dirSetup/constant" .
-    cp -rfL "$dirSetup/system" .
-    cp -rf 0.orig/ 0/
-
-    canCompile || exit 0    # Dynamic code
-
-    if [ ! -d constant/polyMesh ]
+    if [ "$run" = true ]
     then
-
-        runApplication blockMesh
-
-        runApplication renumberMesh -overwrite -constant
-
-        runApplication checkMesh -allTopology -allGeometry -constant
-
-    fi
-
-    if [ "$parallel" = true ]
-    then
-
-        runApplication decomposePar
-
-        runParallel -s parallel renumberMesh -overwrite
-
-        runParallel $(getApplication)
-
-        runApplication reconstructPar
-
+        run_setup "$setup"
     else
-
-        runApplication $(getApplication)
-
+        dry_run_setup "$setup"
     fi
-
-    collect "$setup"
-
 done
+
+
+if notTest "$@" && [ "$run" = true ]
+then
+    ./plot
+fi
 
 
 #------------------------------------------------------------------------------
diff --git a/tutorials/incompressible/simpleFoam/turbulentFlatPlate/plot b/tutorials/incompressible/simpleFoam/turbulentFlatPlate/plot
--- a/tutorials/incompressible/simpleFoam/turbulentFlatPlate/plot
+++ b/tutorials/incompressible/simpleFoam/turbulentFlatPlate/plot
@@ -63,7 +63,7 @@ plot_Rex_vs_Cf() {
 
     plot \
         weighardt(x) t "Weighardt"  w lines lc "red" lw 2, \
-        samples u (\$1 - X0)*Uref/nu:(sqrt(\$2*\$2 + \$3*\$3 + \$4*\$4)/(0.5*Uref*Uref)) \
+        samples u (\$1 - x0)*Uref/nu:(sqrt(\$2*\$2 + \$3*\$3 + \$4*\$4)/(0.5*Uref*Uref)) \
             t "$setup y^+ ${yp}" w l lc "black" lw 2
 PLT_REX_VS_CF
 }
@@ -73,19 +73,19 @@ PLT_REX_VS_CF
 
 # Requires gnuplot
 command -v gnuplot >/dev/null || {
-    echo "FOAM FATAL ERROR: gnuplot not found - skipping graph creation" 1>&2
+    echo "gnuplot not found - skipping graph creation" 1>&2
     exit 1
 }
 
 # Requires awk
 command -v awk >/dev/null || {
-    echo "FOAM FATAL ERROR: awk not found - skipping graph creation" 1>&2
+    echo "awk not found - skipping graph creation" 1>&2
     exit 1
 }
 
 # Check "results" directory
 [ -d "results" ] || {
-    echo "FOAM FATAL ERROR: No results directory found - skipping graph creation" 1>&2
+    echo "No results directory found - skipping graph creation" 1>&2
     exit 1
 }
 
@@ -94,26 +94,26 @@ command -v awk >/dev/null || {
 
 for setup in $setups
 do
-
     for yp in $yps
     do
-
         echo ""
         echo "# Plots for the setup and y+: $setup - $yp"
         echo ""
 
-        dirPlots="plots/$setup/$yp"
+        resultsDir="results/$setup/$yp"
+        [ -d "$resultsDir" ] || {
+            echo "No $resultsDir directory found - skipping graph creation" 1>&2
+            continue
+        }
+
+        dirPlots="plots/$setup"
         [ -d "$dirPlots" ] || mkdir -p "$dirPlots"
 
-        # few manipulations
-        resultsDir="results/$setup/$yp"
         Uref=$(foamDictionary $resultsDir/0/U -entry internalField | sed 's/^.*(\s*\([^ ]*\).*/\1/g')
-        nu=$(foamDictionary $resultsDir/settings/transportProperties -entry nu | sed 's|^.*\s\(.*\);|\1|g')
+        nu=$(foamDictionary $resultsDir/constant/transportProperties -entry nu | sed 's|^.*\s\(.*\);|\1|g')
 
         plot_Rex_vs_Cf "$setup" "$yp" "$Uref" "$nu"
-
     done
-
 done
 
 
diff --git a/tutorials/verificationAndValidation/multiphase/StefanProblem/Allrun b/tutorials/verificationAndValidation/multiphase/StefanProblem/Allrun
--- a/tutorials/verificationAndValidation/multiphase/StefanProblem/Allrun
+++ b/tutorials/verificationAndValidation/multiphase/StefanProblem/Allrun
@@ -1,7 +1,6 @@
 #!/bin/sh
 cd "${0%/*}" || exit                                # Run from this directory
 . ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
-. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
 #------------------------------------------------------------------------------
 
 # settings
@@ -12,57 +11,108 @@ cd "${0%/*}" || exit                                # Run from this directory
     interCondensatingEvaporatingFoam
     "
 
+    # flag to enable computations
+    run=true
+
     # flag to enable computations in parallel mode
     parallel=true
+
+    # flag to enable to use a common mesh
+    common_mesh=true
 
 
 #------------------------------------------------------------------------------
 
 #######################################
-# Collect results into a given path
-# and clean the case for the next run
+# Create the given setup
 # Arguments:
-#    $1 = Path to move results
+#    $1 = Path to create the setup
 # Outputs:
 #    Writes info to stdout
 #######################################
-collect() {
+dry_run_setup() {
 
-    [ $# -eq 0 ] && { echo "Usage: $0 dir-model"; exit 1; }
+    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }
 
-    collection="$1"
+    setup="$1"
+    dirSetup="setups/$setup"
+    dirSetupOrig="setups.orig/$setup"
+    dirOrig="$dirSetupOrig/0.orig"
+    dirConstant="$dirSetupOrig/constant"
+    dirSystem="$dirSetupOrig/system"
 
-    dirResult=results/"$collection"
-    dirSettings="$dirResult"/settings
+    printf "\n# Create the setup: %s\n" "$setup"
+
+    if [ ! -d "$dirSetup" ]
+    then
+        mkdir -p "$dirSetup"
+
+        cp -aRfL "setups.orig/common/." "$dirSetup"
+        cp -afL "$dirSetupOrig"/All* "$dirSetup" 2>/dev/null || :
+        [ -d "$dirOrig" ] && cp -aRfL "$dirOrig/." "$dirSetup/0.orig"
+        [ -d "$dirConstant" ] && cp -aRfL "$dirConstant/." "$dirSetup/constant"
+        [ -d "$dirSystem" ] && cp -aRfL "$dirSystem/." "$dirSetup/system"
+    else
+        printf "\n      # Directory %s already exists\n" "$dirSetup"
+        printf "      # Skipping the creation of a new setup\n"
+    fi
+}
+
+
+#######################################
+# Run the given setup
+# Arguments:
+#    $1 = Path to the setup to run
+# Outputs:
+#    Writes info to stdout
+#######################################
+run_setup() {
+
+    [ $# -eq 0 ] && { echo "Usage error: $0"; exit 1; }
+
+    setup="$1"
+    dirSetup="setups/$setup"
+    dirResult="results/$setup"
+
+    dry_run_setup "$setup"
+    [ -d results ] || mkdir -p results
+
+    printf "\n# Run the setup: %s\n\n" "$setup"
 
     if [ ! -d "$dirResult" ]
     then
+        cp -Rf "$dirSetup" "$dirResult"
 
-        echo "      # Collecting results and settings into $dirResult"
+        if [ "$common_mesh" = true ]
+        then
+            if [ -d results/mesh ]
+            then
+                printf "## Copy the common mesh to the setup: %s\n\n" "$setup"
+                cp -Rf results/mesh/polyMesh "$dirResult"/constant/.
+            fi
+        fi
 
-        mkdir -p "$dirResult"
-        mkdir -p "$dirSettings"
+        if [ "$parallel" = true ]
+        then
+            ( cd "$dirResult" && ./Allrun-parallel )
+        else
+            ( cd "$dirResult" && ./Allrun )
+        fi
 
-        mv -f $(foamListTimes) "$dirResult"
-        [ -d postProcessing ] && mv -f postProcessing "$dirResult"
-        [ -d processor0 ] && mv -f processor* "$dirResult"
-        mv -f log.* "$dirResult"
-        cp -f system/{fv*,controlDict} constant/*Properties "$dirSettings"
-        mv -f 0/ "$dirSettings"
-
-        echo "      # Cleaning up the case"
-
-        cleanTimeDirectories
-        cleanAuxiliary
-        cleanPostProcessing
+        if [ "$common_mesh" = true ]
+        then
+            if [ ! -d results/mesh ]
+            then
+                printf "\n## Store the mesh of %s as the common mesh\n\n" "$setup"
+                mkdir -p results/mesh
+                cp -Rf "$dirResult"/constant/polyMesh results/mesh/.
+            fi
+        fi
 
     else
-
-        echo "      # Directory $dirResult already exists"
-        echo "      # Skipping the computation"
-
+        printf "      # Directory %s already exists\n" "$dirResult"
+        printf "      # Skipping the computation of the given setup\n"
     fi
-
 }
 
 
@@ -70,74 +120,28 @@ collect() {
 
 for setup in $setups
 do
+    dirSetupOrig="setups.orig/$setup"
 
-    echo ""
-    echo "# Computations for the setup: $setup"
-    echo ""
-
-    dirSetup="setups.orig/$setup"
-
-    if [ ! -d "$dirSetup" ]
+    if [ ! -d "$dirSetupOrig" ]
     then
-        echo "Setup directory: $dirSetup" \
+        echo "Setup directory: $dirSetupOrig" \
              "could not be found - skipping execution" 1>&2
-        exit 1
+        continue
     fi
 
-    cp -rfL "$dirSetup/0.orig" .
-    cp -rfL "$dirSetup/constant" .
-    cp -rfL "$dirSetup/system" .
-    cp -rf 0.orig/ 0/
-    cp -rf 0/ 1.36/
-
-    if [ ! -d constant/polyMesh ]
+    if [ "$run" = true ]
     then
-
-        runApplication blockMesh
-
-        runApplication renumberMesh -overwrite -constant
-
-        runApplication checkMesh -allTopology -allGeometry -constant
-
-        if [ ! -f "system/setAlphaFieldDict" ]
-        then
-            if [ -f "system/setAlphaFieldDict.liquid" ]
-            then
-                runApplication -s liquid \
-                    setAlphaField -dict system/setAlphaFieldDict.liquid
-            fi
-
-            if [ -f "system/setAlphaFieldDict.gas" ]
-            then
-                runApplication -s gas \
-                    setAlphaField -dict system/setAlphaFieldDict.gas
-            fi
-        else
-            runApplication setAlphaField
-        fi
-
-    fi
-
-    if [ "$parallel" = true ]
-    then
-
-        runApplication decomposePar
-
-        runParallel -s parallel renumberMesh -overwrite
-
-        runParallel $(getApplication)
-
-        runApplication reconstructPar
-
+        run_setup "$setup"
     else
-
-        runApplication $(getApplication)
-
+        dry_run_setup "$setup"
     fi
-
-    collect "$setup"
-
 done
+
+
+if notTest "$@" && [ "$run" = true ]
+then
+    ./plot
+fi
 
 
 #------------------------------------------------------------------------------
diff --git a/tutorials/verificationAndValidation/multiphase/StefanProblem/plot b/tutorials/verificationAndValidation/multiphase/StefanProblem/plot
--- a/tutorials/verificationAndValidation/multiphase/StefanProblem/plot
+++ b/tutorials/verificationAndValidation/multiphase/StefanProblem/plot
@@ -18,11 +18,11 @@ plot_t_vs_x() {
 
     setup="$1"
 
-    benchmarkFile="$FOAM_TUTORIALS/resources/dataset/StefanProblem.dat"
+    benchmarkFile="resources/dataset/StefanProblem.dat"
 
-    sampleFile0="results/$setup/postProcessing/interfaceHeight1/1.36"
-    sampleFile="$sampleFile0/positionClean.dat"
-    sed -e 's/[()]//g' "$sampleFile0/position.dat" > "$sampleFile"
+    sampleDir="results/$setup/postProcessing/interfaceHeight1/1.36"
+    sampleFile="$sampleDir/positionClean.dat"
+    sed -e 's/[()]//g' "$sampleDir/position.dat" > "$sampleFile"
     image="plots/$setup/t_vs_x.png"
 
     gnuplot<<EOF
@@ -50,13 +50,13 @@ EOF
 
 # Requires gnuplot
 command -v gnuplot >/dev/null || {
-    echo "FOAM FATAL ERROR: gnuplot not found - skipping graph creation" 1>&2
+    echo "gnuplot not found - skipping graph creation" 1>&2
     exit 1
 }
 
 # Check "results" directory
 [ -d "results" ] || {
-    echo "FOAM FATAL ERROR: No results directory found - skipping graph creation" 1>&2
+    echo "No results directory found - skipping graph creation" 1>&2
     exit 1
 }
 
@@ -65,16 +65,19 @@ command -v gnuplot >/dev/null || {
 
 for setup in $setups
 do
-
     echo ""
     echo "# Plots for the setup: $setup"
     echo ""
+
+    [ -d "results/$setup" ] || {
+        echo "No results/$setup directory found - skipping graph creation" 1>&2
+        continue
+    }
 
     dirPlots="plots/$setup"
     [ -d "$dirPlots" ] || mkdir -p "$dirPlots"
 
     plot_t_vs_x "$setup"
-
 done
 
 
