ENH: Added check to see if gnuplot exists on the system before creating graphs

diff --git a/tutorials/combustion/chemFoam/gri/validation/createGraph b/tutorials/combustion/chemFoam/gri/validation/createGraph
--- a/tutorials/combustion/chemFoam/gri/validation/createGraph
+++ b/tutorials/combustion/chemFoam/gri/validation/createGraph
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+type -P gnuplot &>/dev/null || {
+    echo "gnuplot not found - skipping graph creation" >&2
+    exit 1
+}
+
 gnuplot<<EOF
     set terminal postscript eps color enhanced "Helveicta,20"
     set output "OF_vs_CHEMKINII.eps"
