STYLE: use shell 'command' instead of 'which' in tutorials

diff --git a/tutorials/combustion/chemFoam/gri/validation/createGraph b/tutorials/combustion/chemFoam/gri/validation/createGraph
--- a/tutorials/combustion/chemFoam/gri/validation/createGraph
+++ b/tutorials/combustion/chemFoam/gri/validation/createGraph
@@ -1,10 +1,9 @@
 #!/bin/sh
 
-if ! which gnuplot > /dev/null 2>&1
-then
-    echo "gnuplot not found - skipping graph creation" >&2
+command -v gnuplot >/dev/null 2>&1 || {
+    echo "gnuplot not found - skipping graph creation" 1>&2
     exit 1
-fi
+}
 
 gnuplot<<EOF
     set terminal postscript eps color enhanced "Helveicta,20"
diff --git a/tutorials/combustion/chemFoam/ic8h18_TDAC/validation/createGraph b/tutorials/combustion/chemFoam/ic8h18_TDAC/validation/createGraph
--- a/tutorials/combustion/chemFoam/ic8h18_TDAC/validation/createGraph
+++ b/tutorials/combustion/chemFoam/ic8h18_TDAC/validation/createGraph
@@ -1,10 +1,10 @@
 #!/bin/sh
 
-if ! which gnuplot > /dev/null 2>&1
-then
-    echo "gnuplot not found - skipping graph creation" >&2
+# Test if gnuplot exists on the system
+command -v gnuplot >/dev/null 2>&1 || {
+    echo "gnuplot not found - skipping graph creation" 1>&2
     exit 1
-fi
+}
 
 gnuplot<<EOF
     set terminal postscript eps color enhanced "Helvetica,20"
