STYLE: make wmake scripts look more POSIX-like
- also add some comments about the side-effects

diff --git a/wmake/wmake b/wmake/wmake
--- a/wmake/wmake
+++ b/wmake/wmake
@@ -53,7 +53,7 @@
 #     wclean, wcleanPlatform, wcleanLnIncludeAll
 #
 #------------------------------------------------------------------------------
-Script=${0##*/}
+Script=${0##*/}     # Note: need 'Script' for some functions in wmakeFunctions
 
 # Source the wmake functions
 . ${0%/*}/scripts/wmakeFunctions
@@ -127,8 +127,7 @@ useAllCores()
 #------------------------------------------------------------------------------
 
 # Default to compiling the local target only
-all=
-update=
+unset all update
 
 while [ "$#" -gt 0 ]
 do
@@ -141,10 +140,10 @@ do
             export WM_QUIET=1
             ;;
         -a | -all | all)
-            all="all"
+            all=all
             ;;
         -q | -queue | queue)
-            all="queue"
+            all=queue
             ;;
         # Parallel compilation on all cores of local machine
         -j)
@@ -154,13 +153,13 @@ do
             echo "Compiling enabled on $WM_NCOMPPROCS cores"
             ;;
         # Parallel compilation on specified number of cores
-        -j*)
+        -j[1-9]*)
             export WM_NCOMPPROCS=${1#-j}
             echo "Compiling enabled on $WM_NCOMPPROCS cores"
             ;;
         # Non-stop compilation, ignoring errors
         -k | -non-stop)
-            export WM_CONTINUE_ON_ERROR=1
+            export WM_CONTINUE_ON_ERROR=true
             ;;
         # Disable scheduled parallel compilation
         -no-scheduler)
@@ -173,15 +172,15 @@ do
         # - remove empty directories, along with deprecated object directories
         #   and respective binaries.
         -update)
-            update="true"
-            [ -z "$all" ] && all="all"
+            update=true
+            : ${all:=all}  # implies 'all', unless previous set to 'queue' etc.
             ;;
         --)
             shift
             break
             ;;
         -*)
-            usage "unknown option: '$*'"
+            usage "unknown option: '$1'"
             ;;
         *)
             break
@@ -200,10 +199,10 @@ checkEnv
 # When compiling anything but a standalone exe WM_PROJECT and WM_PROJECT_DIR
 # must be set
 [ "$1" = exe -o \( "$WM_PROJECT" -a "$WM_PROJECT_DIR" \) ] || {
-    echo "$Script error:" 1>&2
-    echo "    environment variable \$WM_PROJECT or " \
-         "\$WM_PROJECT_DIR not set" 1>&2
-    echo "    while building project library" 1>&2
+    exec 1>&2
+    echo "$Script error:"
+    echo "    environment variable \$WM_PROJECT or \$WM_PROJECT_DIR not set"
+    echo "    while building project library"
     exit 1
 }
 
@@ -219,11 +218,11 @@ then
     [ $? -eq 0 ] || unset WM_NCOMPPROCS
 fi
 
-if [ "$WM_NCOMPPROCS" ]
+if [ -n "$WM_NCOMPPROCS" ]
 then
     parOpt="-j $WM_NCOMPPROCS"
 
-    if [ "$WM_NCOMPPROCS" -gt 1 -a ! "$MAKEFLAGS" ]
+    if [ "$WM_NCOMPPROCS" -gt 1 -a -z "$MAKEFLAGS" ]
     then
         lockDir=$HOME/.$WM_PROJECT/.wmake
 
@@ -265,7 +264,7 @@ then
     # Specified alternative name for the Make sub-directory:
     [ $# -ge 3 ] && MakeDir=$3
 
-    if [ "$dir" ]
+    if [ -n "$dir" ]
     then
         cd $dir 2>/dev/null || {
             echo "$Script error: could not change to directory '$dir'" 1>&2
@@ -274,16 +273,15 @@ then
     fi
 
     # Print command
-    [ -z "$targetType" ] || targetSpace=" "
-    echo "$Script $targetType$targetSpace${dir:-.}"
+    echo "$Script $targetType${targetType:+ }${dir:-.}"
 fi
 
 
 #------------------------------------------------------------------------------
-# Recurse the source tree to compile "all" targets
+# Recurse the source tree to update all
 #------------------------------------------------------------------------------
 
-if [ -n "$update" ]
+if [ "$update" = true ]
 then
     wrmdep -update
     wrmdep -old
@@ -297,40 +295,37 @@ fi
 # Recurse the source tree to compile "all" targets
 #------------------------------------------------------------------------------
 
-if [ "$all" = "all" ]
+if [ "$all" = all ]
 then
     if [ -e Allwmake ]
     then
         ./Allwmake -fromWmake $targetType
         exit $?
+    fi
+
+    # Find all the sub-directories containing a 'Make' directory
+    # (xargs is just used to flatten the list)
+    FOAM_APPS=$(
+        for d in *
+        do [ -d "$d" -a "$d" != Optional -a "$d" != Make ] && echo "$d"
+        done | xargs)
+
+    if [ -n "$FOAM_APPS" ]
+    then
+        # Compile all applications in sub-directories
+        $make ${WM_CONTINUE_ON_ERROR:+-k} \
+              -f $WM_DIR/makefiles/apps \
+              TARGET="$targetType" FOAM_APPS="$FOAM_APPS"
+        makeExitCode=$?
     else
-        # Have to keep track of the main exit code for the call to "make"
-        makeExitCode=0
+        makeExitCode=0 # For fall-through
+    fi
 
-        # Find all the sub-directories containing a 'Make' directory
-        FOAM_APPS=$(\
-                       for d in *; \
-                       do [ -d "$d" -a "$d" != Optional -a "$d" != Make ] \
-                          && echo "$d"; \
-                       done | xargs \
-                 )
-        if [ ! "$FOAM_APPS" = "" ]
-        then
-            # Compile all applications in sub-directories
-            $make ${WM_CONTINUE_ON_ERROR:+-k} \
-                  -f $WM_DIR/makefiles/apps \
-                  TARGET="$targetType" FOAM_APPS="$FOAM_APPS"
-            makeExitCode=$?
-        fi
-        # If the current directory contains a 'Make' directory continue
-        # otherwise exit, or always exit in case of error
-        if [ ! -d $MakeDir -o $makeExitCode -ne 0 ]
-        then
-            exit $makeExitCode
-        fi
-
-        # Clean up tracking variable
-        unset makeExitCode
+    # Exit if current directory does not contains a 'Make' directory or
+    # an error was previously encountered
+    if [ ! -d "$MakeDir" -o $makeExitCode -ne 0 ]
+    then
+        exit $makeExitCode
     fi
 fi
 
@@ -339,9 +334,9 @@ fi
 # Recurse the source tree to compile "all" targets using wmakeQueue
 #------------------------------------------------------------------------------
 
-if [ "$all" = "queue" ]
+if [ "$all" = queue ]
 then
-    [ -n "$update" ] || wmakeLnIncludeAll $parOpt
+    [ "$update" = true ] || wmakeLnIncludeAll $parOpt
 
     (
         export WM_COLLECT_DIR=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}/${PWD////_}
@@ -369,20 +364,18 @@ cdSource
 
 # Transform no option to "libso" if that looks appropriate or remove it
 # so that the call to make builds the application
-if [ "$targetType" = "" ]
+if [ -z "$targetType" ]
 then
-    unset targetType
-    if grep -e '^ *LIB *=' "$MakeDir/files" >/dev/null 2>&1
+    if grep -qe '^ *LIB *=' "$MakeDir/files" 2>/dev/null
     then
         targetType=libso
     fi
-elif grep -e '^ *EXE *=' "$MakeDir/files" >/dev/null 2>&1
+elif grep -qe '^ *EXE *=' "$MakeDir/files" 2>/dev/null
 then
     # Application. Remove any nonsense targetType
     case "$targetType" in
-      lib*)
+    lib*)
         unset targetType
-        break
         ;;
     esac
 fi
@@ -396,8 +389,8 @@ fi
 objectsDir=$MakeDir/$WM_OPTIONS
 if [ $(echo $PWD | grep "$WM_PROJECT_DIR") ]
 then
-    platformPath=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}
-    objectsDir=$platformPath$(echo $PWD | sed s%$WM_PROJECT_DIR%% )
+    buildPath=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}
+    objectsDir=$buildPath$(echo $PWD | sed s%$WM_PROJECT_DIR%%)
 fi
 
 (
@@ -429,16 +422,15 @@ fi
 # Make the dependency files
 #------------------------------------------------------------------------------
 
-# For libraries create lnInclude ...
+# For libraries create lnInclude, but only if 'LIB' is declared in 'Make/files'
 case "$targetType" in
-    lib | libo | libso | dep )
-        # ... but only if 'LIB' is declared in 'Make/files'
-        if grep -e '^ *LIB *=' "$MakeDir/files" >/dev/null 2>&1
-        then
-            $make -s -f $WM_DIR/makefiles/general MAKE_DIR=$MakeDir \
-                  OBJECTS_DIR=$objectsDir lnInclude
-        fi
-        ;;
+(lib | libo | libso | dep)
+    if grep -qe '^ *LIB *=' "$MakeDir/files" 2>/dev/null
+    then
+        $make -s -f $WM_DIR/makefiles/general MAKE_DIR=$MakeDir \
+              OBJECTS_DIR=$objectsDir lnInclude
+    fi
+    ;;
 esac
 
 
@@ -453,12 +445,7 @@ then
         OBJECTS_DIR=$objectsDir updatedep
     makeExitCode=$?
 
-    if [ $makeExitCode -ne 0 ]
-    then
-        exit $makeExitCode
-    fi
-
-    unset makeExitCode
+    [ $makeExitCode -eq 0 ] || exit $makeExitCode
 fi
 
 
@@ -469,12 +456,6 @@ fi
 exec $make -f $WM_DIR/makefiles/general MAKE_DIR=$MakeDir \
      OBJECTS_DIR=$objectsDir $targetType
 
-
-#------------------------------------------------------------------------------
-# Cleanup local variables and functions
-#------------------------------------------------------------------------------
-
-unset Script usage useAllCores update expandPath findTarget
-
+exit 0 # clean exit
 
 #------------------------------------------------------------------------------
