ENH: improvements for handling update of build information
- When building OpenFOAM for different platform combinations
  (single/double, int32/int64) the build information that is compiled
  into the OpenFOAM lib can become out of sync.

  This is because the update trigger (wmakeBuildInfo -check) is
  independent of the targetted platform. The added file
  'src/OpenFOAM/Alltouch' provides a direct means of forcing a rebuild
  of the version information. Eg,

      src/OpenFOAM/Alltouch
      wmake src/OpenFOAM

  Also provide an additional 'wmakeBuildInfo -remove' to forcibly
  remove META-INFO/build-info, if that is desired.

diff --git a/wmake/wrmdep b/wmake/wrmdep
--- a/wmake/wrmdep
+++ b/wmake/wrmdep
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2017 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2017-2019 OpenCFD Ltd.
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 #                           | Copyright (C) 2015-2016 OpenFOAM Foundation
@@ -65,9 +65,9 @@ Usage:
 
 $Script [-a | -all | all] [file1 [..fileN]]
 
-    Remove all .dep files or remove .dep files referring to <file>
-    With the -a/-all/all option the .dep files are removed for all
-    platforms rather than just the current platform ($WM_OPTIONS).
+    Remove all .dep files or remove .dep files referring to <file>.
+    With the 'all' option the .dep files are removed for all platforms
+    rather than just the current platform ($WM_OPTIONS).
 
 $Script [-o | -old] [dir1 [..dirN]]
 
@@ -79,9 +79,9 @@ $Script [-o | -old] [dir1 [..dirN]]
 
 $Script -update
 
-    Search all the "src" and "application" directories of the project for
-    broken symbolic links for source code files and then remove all .dep
-    files that relate to files that no longer exist.
+    Search "src" and "application" directories of the project for broken
+    symbolic links for source code files and remove all .dep files related
+    to files that no longer exist.
     Must be executed in the project top-level directory:
         $WM_PROJECT_DIR
 
@@ -98,27 +98,22 @@ USAGE
 rmdepMode=files
 
 # Default to processing only the current platform
-unset all
+unset platform
 
 while [ "$#" -gt 0 ]
 do
     case "$1" in
-    # Print help
     -h | -help*)
         usage
         ;;
-    # All platforms
-    -a | -all | all)
-        all=all
-        shift
+    -a | -all | all)    # All platforms
+        platform=all
         ;;
     -o | -old)
         rmdepMode=oldFolders
-        shift
         ;;
     -update)
         rmdepMode=updateMode
-        shift
         ;;
     -*)
         usage "unknown option: '$1'"
@@ -127,13 +122,14 @@ do
         break
         ;;
     esac
+    shift
 done
-#------------------------------------------------------------------------------
 
 # Check environment variables
 checkEnv
 
 
+#------------------------------------------------------------------------------
 case "$rmdepMode" in
 files)
 
@@ -143,22 +139,21 @@ files)
 
     objectsDir=$(findObjectDir .) || exit 1 # Fatal
 
-    # With the -a/-all option replace the current platform with a wildcard
-    if [ "$all" = all ]
+    # With -a/-all option: replace the current platform with a wildcard
+    if [ "$platform" = all ]
     then
-        objectsDir=$(echo $objectsDir | sed s%$WM_OPTIONS%*% )
+        objectsDir=$(echo "$objectsDir" | sed "s%$WM_OPTIONS%*%")
     fi
 
     if [ "$#" -eq 0 ]
     then
-        echo "removing all .dep files ..."
-        find $objectsDir -name '*.dep' -type f -delete -print
+        echo "Removing all .dep files ..." 1>&2
+        find "$objectsDir" -name '*.dep' -type f -delete -print
     else
-        echo "removing .o files corresponding to"
-        echo "    $@ ..."
+        echo "Removing .dep files for: $*" 1>&2
         for file
         do
-            find $objectsDir -name '*.dep' -type f \
+            find "$objectsDir" -name '*.dep' -type f \
                 -exec grep -q "$file" {} \; -delete -print
         done
     fi
@@ -168,29 +163,29 @@ oldFolders)
     # Default is the current directory
     [ "$#" -gt 0 ] || set -- .
 
-    echo "Removing dep files that refer to source files that no longer exist..."
+    echo "Removing dep files for non-existent source files ..." 1>&2
 
     for checkDir
     do
-        objectsDir=$(findObjectDir $checkDir)
+        objectsDir=$(findObjectDir "$checkDir")
 
         if [ -d "$objectsDir" ]
         then
-            echo "    searching: $objectsDir"
+            echo "    searching: $objectsDir" 1>&2
         else
-            echo "    skipping non-dir: $objectsDir"
+            echo "    skipping non-dir: $objectsDir" 1>&2
             continue
         fi
 
-        find $objectsDir -name '*.dep' -type f -print | while read depFile
+        find "$objectsDir" -name '*.dep' -type f -print | while read depFile
         do
-            sourceFile=$(depToSource $depFile)
+            sourceFile=$(depToSource "$depFile")
 
             # Check C++ or Flex source file exists
             if [ ! -r "$sourceFile" ]
             then
-                echo "    rm $depFile"
-                rm -f $depFile 2>/dev/null
+                echo "    rm $depFile" 1>&2
+                rm -f "$depFile" 2>/dev/null
             fi
         done
     done
@@ -199,24 +194,24 @@ oldFolders)
 updateMode)
     if [ "$PWD" != "$WM_PROJECT_DIR" ]
     then
-        echo "Cannot 'update', not in the project top-level directory" 1>&2
+        echo "Cannot 'update', not in project top-level directory" 1>&2
         exit 1
     fi
 
-    echo "Removing dep files corresponding to source files that no longer exist..."
+    echo "Removing dep files for non-existent source files ..." 1>&2
     fileNameList=$(find -L src applications -name '*.[CHL]' -type l)
 
     for filePathAndName in $fileNameList
     do
-        fileName=$(basename $filePathAndName)
+        fileName=$(basename "$filePathAndName")
         for subdir in src applications
         do
-            echo "    '$subdir': $fileName"
-            (cd $subdir && $Script -a $fileName)
+            echo "    '$subdir': $fileName" 1>&2
+            (cd $subdir && $Script -all "$fileName")
         done
 
         # Just in case, remove the symbolic link as the last step
-        unlink $filePathAndName
+        unlink "$filePathAndName"
     done
     ;;
 
