ENH: minor improvements to environment
- handle sourcing bashrc with a relative path (issue #383)
- handle sourcing from bash and zsh.
  Still need manual intervention when sourcing dash, sh, or ksh.
- replace grep in etc/cshrc with sed only
- logical instead of physical path for WM_PROJECT_DIR (issue #431).
  Doesn't seem to be possible for csh/tcsh.

  * Continue using physical locations when comparing directories,
    but not for the top-level FOAM_INST_DIR, WM_PROJECT_DIR.

- relocate WM_CC, WM_CXX overrides from etc/config.*/compiler
  to etc/config.*/settings to ensure that they are left untouched
  when etc/config.sh/compiler is sourced while making third-party
  packages (eg, gcc, llvm, CGAL).

- provide fallback FOAM_TUTORIALS setting in RunFunctions

STYLE: remove "~OpenFOAM" fallback as being too rare, non-obvious

diff --git a/etc/config.csh/settings b/etc/config.csh/settings
--- a/etc/config.csh/settings
+++ b/etc/config.csh/settings
@@ -39,11 +39,10 @@ alias _foamAddMan 'setenv MANPATH \!*\:${MANPATH}'
 
 #------------------------------------------------------------------------------
 # Set environment variables according to system type
+if (! $?WM_OSTYPE ) setenv WM_OSTYPE POSIX  # Default is POSIX
+setenv WM_COMPILER_LIB_ARCH  # Set, but empty: default for 32bit
+
 setenv WM_ARCH `uname -s`
-
-# Default WM_COMPILER_LIB_ARCH for 32bit
-setenv WM_COMPILER_LIB_ARCH
-
 switch ($WM_ARCH)
 case Linux:
     setenv WM_ARCH linux
@@ -54,7 +53,7 @@ case Linux:
         breaksw
 
     case x86_64:
-        if ( ! $?WM_ARCH_OPTION ) setenv WM_ARCH_OPTION 64  # Default to 64-bit
+        if (! $?WM_ARCH_OPTION ) setenv WM_ARCH_OPTION 64  # Default to 64-bit
         switch ($WM_ARCH_OPTION)
         case 32:
             setenv WM_COMPILER_ARCH 64
@@ -136,7 +135,6 @@ UNSUPPORTED_OS
 
 endsw
 
-
 #------------------------------------------------------------------------------
 
 # Location of the jobControl directory
@@ -202,37 +200,49 @@ _foamAddPath ${FOAM_USER_APPBIN}:${FOAM_SITE_APPBIN}:${FOAM_APPBIN}
 # Make sure to pick up dummy versions of external libraries last
 _foamAddLib  ${FOAM_USER_LIBBIN}:${FOAM_SITE_LIBBIN}:${FOAM_LIBBIN}:${FOAM_EXT_LIBBIN}:${FOAM_LIBBIN}/dummy
 
+#------------------------------------------------------------------------------
+
 # Compiler settings
 # ~~~~~~~~~~~~~~~~~
+
+# Default to system compiler
+if (! $?WM_COMPILER_TYPE ) setenv WM_COMPILER_TYPE system
+
+# Adjustments for non-gcc compilers
+switch ("$WM_COMPILER")
+case Clang*:
+    # Using clang - not gcc
+    setenv WM_CC 'clang'
+    setenv WM_CXX 'clang++'
+    breaksw
+case Icc*:
+    # Using icc - not gcc
+    setenv WM_CC 'icc'
+    setenv WM_CXX 'icpc'
+    breaksw
+endsw
+
+# Clear prior to sourcing
 unset gcc_version gmp_version mpfr_version mpc_version
 unsetenv GMP_ARCH_PATH MPFR_ARCH_PATH
 
-# Compiler installation - default to system
-# ~~~~~~~~~~~~~~~~~~~~~
-if ( ! $?WM_COMPILER_TYPE ) setenv WM_COMPILER_TYPE system
-
-# Load configured compiler versions, regardless of the compiler type
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Load pre-defined compiler versions
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 _foamEtc config.csh/compiler
 
-switch ("$WM_COMPILER_TYPE")
-case system:
-    # Use system compiler
-    breaksw
+switch ("$WM_COMPILER_TYPE-$WM_COMPILER")
+case ThirdParty-Gcc*:
+    if (! $?gmp_version  ) set gmp_version=gmp-system
+    if (! $?mpfr_version ) set mpfr_version=mpfr-system
+    if (! $?mpc_version  ) set mpc_version=mpc-system
+    set gccDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gcc_version
+    set gmpDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gmp_version
+    set mpfrDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$mpfr_version
+    set mpcDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$mpc_version
 
-case ThirdParty:
-    if ( $?gcc_version ) then
-        if ( ! $?gmp_version  ) set gmp_version=gmp-system
-        if ( ! $?mpfr_version ) set mpfr_version=mpfr-system
-        if ( ! $?mpc_version  ) set mpc_version=mpc-system
-        set gccDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gcc_version
-        set gmpDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gmp_version
-        set mpfrDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$mpfr_version
-        set mpcDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$mpc_version
-
-        # Check that the compiler directory can be found
-        if ( ! -d "$gccDir" ) then
-            /bin/cat << GCC_NOT_FOUND
+    # Check that the compiler directory can be found
+    if ( ! -d "$gccDir" ) then
+        /bin/cat << GCC_NOT_FOUND
 ===============================================================================
 Warning in $WM_PROJECT_DIR/etc/config.csh/settings:
 Cannot find '$WM_COMPILER' compiler installation
@@ -242,39 +252,39 @@ Cannot find '$WM_COMPILER' compiler installation
     WM_COMPILER_TYPE to 'system' in \$WM_PROJECT_DIR/etc/cshrc.
 ===============================================================================
 GCC_NOT_FOUND
-        endif
-
-        _foamAddMan     $gccDir/man
-        _foamAddPath    $gccDir/bin
-
-        # Add ThirdParty compiler libraries to run-time environment
-        _foamAddLib     $gccDir/lib$WM_COMPILER_LIB_ARCH
-
-        # Add ThirdParty gmp/mpfr/mpc libraries to run-time environment
-        if ( "${gmpDir:t}" != "gmp-system" ) then
-            _foamAddLib $gmpDir/lib$WM_COMPILER_LIB_ARCH
-            setenv GMP_ARCH_PATH $gmpDir        # For ThirdParty CGAL
-        endif
-        if ( "${mpfrDir:t}" != "mpfr-system" ) then
-            _foamAddLib $mpfrDir/lib$WM_COMPILER_LIB_ARCH
-            setenv MPFR_ARCH_PATH $mpfrDir      # For ThirdParty CGAL
-        endif
-        if ( "${mpcDir:t}" != "mpc-system" ) then
-            _foamAddLib $mpcDir/lib$WM_COMPILER_LIB_ARCH
-        endif
-
-        if ($?FOAM_VERBOSE && $?prompt) then
-            echo "Using ThirdParty compiler"
-            echo "    ${gccDir:t} (${gmpDir:t} ${mpfrDir:t} ${mpcDir:t})"
-        endif
     endif
 
-    if ( $?clang_version ) then
-        set clangDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$clang_version
+    _foamAddMan     $gccDir/man
+    _foamAddPath    $gccDir/bin
 
-        # Check that the compiler directory can be found
-        if ( ! -d "$clangDir" ) then
-            /bin/cat << CLANG_NOT_FOUND
+    # Add ThirdParty compiler libraries to run-time environment
+    _foamAddLib     $gccDir/lib$WM_COMPILER_LIB_ARCH
+
+    # Add ThirdParty gmp/mpfr/mpc libraries to run-time environment
+    if ( "${gmpDir:t}" != "gmp-system" ) then
+        _foamAddLib $gmpDir/lib$WM_COMPILER_LIB_ARCH
+        setenv GMP_ARCH_PATH $gmpDir        # For ThirdParty CGAL
+    endif
+    if ( "${mpfrDir:t}" != "mpfr-system" ) then
+        _foamAddLib $mpfrDir/lib$WM_COMPILER_LIB_ARCH
+        setenv MPFR_ARCH_PATH $mpfrDir      # For ThirdParty CGAL
+    endif
+    if ( "${mpcDir:t}" != "mpc-system" ) then
+        _foamAddLib $mpcDir/lib$WM_COMPILER_LIB_ARCH
+    endif
+
+    if ($?FOAM_VERBOSE && $?prompt) then
+        echo "Using ThirdParty compiler"
+        echo "    ${gccDir:t} (${gmpDir:t} ${mpfrDir:t} ${mpcDir:t})"
+    endif
+    breaksw
+
+case ThirdParty-Clang*:
+    set clangDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$clang_version
+
+    # Check that the compiler directory can be found
+    if ( ! -d "$clangDir" ) then
+        /bin/cat << CLANG_NOT_FOUND
 ===============================================================================
 Warning in $WM_PROJECT_DIR/etc/config.csh/settings:
 Cannot find '$WM_COMPILER' compiler installation
@@ -284,20 +294,20 @@ Cannot find '$WM_COMPILER' compiler installation
     WM_COMPILER_TYPE to 'system' in \$WM_PROJECT_DIR/etc/cshrc.
 ===============================================================================
 CLANG_NOT_FOUND
-        endif
-
-        _foamAddMan     $clangDir/man
-        _foamAddPath    $clangDir/bin
-
-        if ($?FOAM_VERBOSE && $?prompt) then
-            echo "Using ThirdParty compiler"
-            echo "    ${clangDir:t}"
-        endif
     endif
 
-    unset gcc_version gccDir
-    unset gmp_version gmpDir  mpfr_version mpfrDir  mpc_version mpcDir
-    unset clang_version clangDir
+    _foamAddMan     $clangDir/man
+    _foamAddPath    $clangDir/bin
+
+    if ($?FOAM_VERBOSE && $?prompt) then
+        echo "Using ThirdParty compiler"
+        echo "    ${clangDir:t}"
+    endif
+    breaksw
+
+case system-*:
+case ThirdParty-*:
+    # Using system compiler or other ThirdParty compiler
     breaksw
 
 default:
@@ -312,9 +322,12 @@ UNKNOWN_TYPE
 
 endsw
 
+# Cleanup
+# ~~~~~~~
+unset gcc_version gccDir
+unset gmp_version gmpDir  mpfr_version mpfrDir  mpc_version mpcDir
+unset clang_version clangDir
+# Retain: _foamAddPath _foamAddLib _foamAddMan
 
-# Cleanup environment:
-# ~~~~~~~~~~~~~~~~~~~~
-#- keep _foamAddPath _foamAddLib _foamAddMan
 
 #------------------------------------------------------------------------------
diff --git a/etc/config.sh/settings b/etc/config.sh/settings
--- a/etc/config.sh/settings
+++ b/etc/config.sh/settings
@@ -29,10 +29,10 @@
 #     Sourced from OpenFOAM-<VERSION>/etc/bashrc
 #
 #------------------------------------------------------------------------------
-
 # Set environment variables according to system type
-export WM_ARCH=$(uname -s)
+: ${WM_OSTYPE:=POSIX}; export WM_OSTYPE  # Default is POSIX
 
+export WM_ARCH=$(uname -s)
 case "$WM_ARCH" in
 Linux)
     WM_ARCH=linux
@@ -201,34 +201,45 @@ _foamAddPath $FOAM_USER_APPBIN:$FOAM_SITE_APPBIN:$FOAM_APPBIN
 # Make sure to pick up dummy versions of external libraries last
 _foamAddLib  $FOAM_USER_LIBBIN:$FOAM_SITE_LIBBIN:$FOAM_LIBBIN:$FOAM_EXT_LIBBIN:$FOAM_LIBBIN/dummy
 
+#------------------------------------------------------------------------------
+
 # Compiler settings
 # ~~~~~~~~~~~~~~~~~
+
+# Default to system compiler
+: ${WM_COMPILER_TYPE:=system}; export WM_COMPILER_TYPE
+
+# Adjust for non-gcc compilers
+case "$WM_COMPILER" in
+Clang*)
+    # Using clang - not gcc
+    export WM_CC='clang'
+    export WM_CXX='clang++'
+    ;;
+Icc*)
+    # Using icc - not gcc
+    export WM_CC='icc'
+    export WM_CXX='icpc'
+    ;;
+esac
+
+# Clear prior to sourcing
 unset gcc_version gmp_version mpfr_version mpc_version
 unset GMP_ARCH_PATH MPFR_ARCH_PATH
 
-# Compiler installation - default to system
-# ~~~~~~~~~~~~~~~~~~~~~
-: ${WM_COMPILER_TYPE:=system}; export WM_COMPILER_TYPE
-
-# Load configured compiler versions, regardless of the compiler type
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Load pre-defined compiler versions
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 _foamEtc config.sh/compiler
 
-case "$WM_COMPILER_TYPE" in
-system)
-    # Use system compiler
-    ;;
+case "$WM_COMPILER_TYPE-$WM_COMPILER" in
+ThirdParty-Gcc*)
+    gccDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gcc_version
+    gmpDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/${gmp_version:-gmp-system}
+    mpfrDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/${mpfr_version:-mpfr-system}
+    mpcDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/${mpc_version:-mpc-system}
 
-ThirdParty)
-    if [ -n "$gcc_version" ]
-    then
-        gccDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gcc_version
-        gmpDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/${gmp_version:-gmp-system}
-        mpfrDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/${mpfr_version:-mpfr-system}
-        mpcDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/${mpc_version:-mpc-system}
-
-        # Check that the compiler directory can be found
-        [ -d "$gccDir" ] || /bin/cat << GCC_NOT_FOUND 1>&2
+    # Check that the compiler directory can be found
+    [ -d "$gccDir" ] || /bin/cat << GCC_NOT_FOUND 1>&2
 ===============================================================================
 Warning in $WM_PROJECT_DIR/etc/config.sh/settings:
 Cannot find '$WM_COMPILER' compiler installation
@@ -239,41 +250,40 @@ Cannot find '$WM_COMPILER' compiler installation
 ===============================================================================
 GCC_NOT_FOUND
 
-        _foamAddMan     $gccDir/man
-        _foamAddPath    $gccDir/bin
+    _foamAddMan     $gccDir/man
+    _foamAddPath    $gccDir/bin
 
-        # Add ThirdParty compiler libraries to run-time environment
-        _foamAddLib     $gccDir/lib$WM_COMPILER_LIB_ARCH
+    # Add ThirdParty compiler libraries to run-time environment
+    _foamAddLib     $gccDir/lib$WM_COMPILER_LIB_ARCH
 
-        # Add ThirdParty gmp/mpfr/mpc libraries to run-time environment
-        if [ "${gmpDir##*-}" != system ]
-        then
-            _foamAddLib $gmpDir/lib$WM_COMPILER_LIB_ARCH
-            export GMP_ARCH_PATH=$gmpDir        # For ThirdParty CGAL
-        fi
-        if [ "${mpfrDir##*-}" != system ]
-        then
-            _foamAddLib $mpfrDir/lib$WM_COMPILER_LIB_ARCH
-            export MPFR_ARCH_PATH=$mpfrDir      # For ThirdParty CGAL
-        fi
-        if [ "${mpcDir##*-}" != system ]
-        then
-            _foamAddLib $mpcDir/lib$WM_COMPILER_LIB_ARCH
-        fi
-
-        if [ "$FOAM_VERBOSE" -a "$PS1" ]
-        then
-            echo "Using ThirdParty compiler"
-            echo "    ${gccDir##*/}  (${gmpDir##*/}  $${mpfrDir##*/}  ${mpcDir##*/})"
-        fi
+    # Add ThirdParty gmp/mpfr/mpc libraries to run-time environment
+    if [ "${gmpDir##*-}" != system ]
+    then
+        _foamAddLib $gmpDir/lib$WM_COMPILER_LIB_ARCH
+        export GMP_ARCH_PATH=$gmpDir        # For ThirdParty CGAL
+    fi
+    if [ "${mpfrDir##*-}" != system ]
+    then
+        _foamAddLib $mpfrDir/lib$WM_COMPILER_LIB_ARCH
+        export MPFR_ARCH_PATH=$mpfrDir      # For ThirdParty CGAL
+    fi
+    if [ "${mpcDir##*-}" != system ]
+    then
+        _foamAddLib $mpcDir/lib$WM_COMPILER_LIB_ARCH
     fi
 
-    if [ -n "$clang_version" ]
+    if [ "$FOAM_VERBOSE" -a "$PS1" ]
     then
-        clangDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$clang_version
+        echo "Using ThirdParty compiler"
+        echo "    ${gccDir##*/}  (${gmpDir##*/}  $${mpfrDir##*/}  ${mpcDir##*/})"
+    fi
+    ;;
 
-        # Check that the compiler directory can be found
-        [ -d "$clangDir" ] || /bin/cat << CLANG_NOT_FOUND 1>&2
+ThirdParty-Clang*)
+    clangDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$clang_version
+
+    # Check that the compiler directory can be found
+    [ -d "$clangDir" ] || /bin/cat << CLANG_NOT_FOUND 1>&2
 ===============================================================================
 Warning in $WM_PROJECT_DIR/etc/config.sh/settings:
 Cannot find '$WM_COMPILER' compiler installation
@@ -284,20 +294,20 @@ Cannot find '$WM_COMPILER' compiler installation
 ===============================================================================
 CLANG_NOT_FOUND
 
-        _foamAddMan     $clangDir/share/man
-        _foamAddPath    $clangDir/bin
+    _foamAddMan     $clangDir/share/man
+    _foamAddPath    $clangDir/bin
 
-        if [ "$FOAM_VERBOSE" -a "$PS1" ]
-        then
-            echo "Using ThirdParty compiler"
-            echo "    ${clangDir##*/}"
-        fi
+    if [ "$FOAM_VERBOSE" -a "$PS1" ]
+    then
+        echo "Using ThirdParty compiler"
+        echo "    ${clangDir##*/}"
     fi
-
-    unset gcc_version gccDir
-    unset gmp_version gmpDir  mpfr_version mpfrDir  mpc_version mpcDir
-    unset clang_version clangDir
     ;;
+
+system-* | ThirdParty-*)
+    # Using system compiler or other ThirdParty compiler
+    ;;
+
 *)
     /bin/cat << UNKNOWN_TYPE 1>&2
 ===============================================================================
@@ -309,5 +319,12 @@ UNKNOWN_TYPE
     ;;
 
 esac
+
+
+# Cleanup
+# ~~~~~~~
+unset gcc_version gccDir
+unset gmp_version gmpDir  mpfr_version mpfrDir  mpc_version mpcDir
+unset clang_version clangDir
 
 #------------------------------------------------------------------------------
