ENH: InjectedParticleDistributionInjection  model - added protection for the case of zero particles; updated tutorial scripts.  See #363

diff --git a/tutorials/multiphase/interFoam/laminar/vofToLagrangian/lagrangianParticleInjection/Allrun b/tutorials/multiphase/interFoam/laminar/vofToLagrangian/lagrangianParticleInjection/Allrun
--- a/tutorials/multiphase/interFoam/laminar/vofToLagrangian/lagrangianParticleInjection/Allrun
+++ b/tutorials/multiphase/interFoam/laminar/vofToLagrangian/lagrangianParticleInjection/Allrun
@@ -25,7 +25,7 @@ copyLagrangianData()
 
     if [ -z $latestTime ]
     then
-        echo "Error: unable to find Lagrangian data in case $eulerianCase"
+        echo "Error: unable to find Lagrangian data in case $dir"
         exit 1
     fi
 
@@ -37,6 +37,7 @@ copyLagrangianData()
         \cp -r $dir 0
     else
         echo "Error: unable to find Lagrangian data in case $dir"
+        exit 1
     fi
 }
 
