COMP: skip compilation of plugins if include files are missing (fixes #464)

diff --git a/applications/utilities/postProcessing/graphics/PVReaders/Allwmake b/applications/utilities/postProcessing/graphics/PVReaders/Allwmake
--- a/applications/utilities/postProcessing/graphics/PVReaders/Allwmake
+++ b/applications/utilities/postProcessing/graphics/PVReaders/Allwmake
@@ -25,6 +25,14 @@ canBuildPlugin()
         return 1
     }
 
+    [ -d "$ParaView_INCLUDE_DIR" ] && \
+    [ -f "$ParaView_INCLUDE_DIR/pqServerManagerModel.h" ] || {
+        echo "==> cannot build ParaView plugins without an include directory"
+        echo "    ... or without GUI support"
+        echo "    ParaView_INCLUDE_DIR=$ParaView_INCLUDE_DIR"
+        return 1
+    }
+
     type cmake > /dev/null 2>&1 || {
         echo "==> cannot build ParaView plugins without cmake"
         return 1
